window.ClaraStories = [
  {
    id: "rizwanea-sacrifice",
    theme: "sacrifice",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Sacrifice",
    title: "Rizwanea asks for one more day.",
    quote: "Teach me to be grateful!",
    readTime: "5 minute read",
    tags: ["Sacrifice", "Detachment", "Gratitude", "Marriage", "Service"],
    summary:
      "After years of travel, teaching, and rootlessness, Rizwanea reaches the end of her strength and spends one decisive day in prayer.",
    source: "https://bahaistories.com/subject/sacrifice",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Wilmette_how_side.jpg",
    featureImageAlt: "Bahá'í House of Worship in Wilmette seen from the side",
    story: [
      "Mable Ives, after she married Howard Colby Ives, became known to many who loved her as Rizwanea. For very many years, after they were married, my father and Rizwanea traveled and taught the Faith. It was their entire life.",
      "They traveled through the New England states, through Pennsylvania, Ohio, Illinois, New York and many many more - always teaching, always leaving an established Assembly behind them. It was a gypsy life.",
      "It meant that never once, during all the years, did they really have a home; no place where they might be surrounded by their own things, where they might put down roots. Always they lived surrounded by strange and alien furniture, by the bare wall and arid atmosphere of barren hotels, boarding houses, and cubbyholes where they might sleep while, during their waking hours, they earned their living and taught their beloved Faith.",
      "At last, after many years, with her health failing, Rizwanea felt she could endure no more. She had come to the end. She must have a home. She needed it with every atom of her being - needed it as a bird needs to make a nest in the springtime or as anyone, weary and spent, needs to rest in the sun.",
      "At this time they - she and my father were living in a particularly difficult situation. It was a furnished room and the landlady was constantly complaining of everything they did. They used too many lights, they took too many showers using up too much water, and the clacking of Father's typewriter was driving her crazy.",
      "So, one morning, Rizwanea told Father how she felt: She had come to the end; she could endure no more; she was unable to go one step farther. They had a long period of consultation, and at the end, Father told her that, of course, he would do as she wished, but would she, in turn, do one thing for him? Would she wait just one more day before making a truly final decision - and would she spend this day in prayer?",
      "She agreed. So after Father had left her to go out and attend to his business details, she kept her promise. She began to pray. And as she prayed, it came to her just what, in its depth and beauty, submission, detachment, and servitude really meant. And it came to her that submission - true and complete submission to the Will of God - was the first basic step.",
      "So she began to pray for submission - she prayed and prayed, and finally, submission came to her - but with it came the realization that submission was not enough. Well, then, what was enough? What should she pray for now?",
      "And she remembered that Bahá'u'lláh had written that we must be grateful for the circumstances to which we were submitting. Grateful? Grateful for this horrid little room? Grateful for the beastly, complaining landlady? Well, all right - if Bahá'u'lláh said so she, Rizwanea, would be grateful. But it wasn't easy. She was pacing the room, thinking, praying, fighting and now she went to the window to stare out into the street.",
      "'Teach me to be grateful! Teach me to be submissive! I will be grateful! I will be submissive!' She clenched her small fists. She fought and she suffered. And, finally, the first warm touch and then the warmer flow of submissive gratitude surged over her.",
      "But, the next moment, she realized that even this was not enough. Not enough? When she'd fought so hard and she was so tired. What then was left? What should she pray for next?",
      "And it came to her that now she must pray for love. Love for her nerve-wracking circumstances; love for her harsh landlady; love for the whole situation that had led to the crisis - the blessed crisis that had forced her to learn this lesson.",
      "So, now, Rizwanea prayed that she might love, that she might be filled with love, that she might be able to pour out this love. And her prayers were answered.",
      "When Father returned to her, it was to meet a radiant woman - a woman filled with the glory of complete submission to the Will of God - a woman rich with the glory of gratitude for tests - a woman overflowing with the clear crystal waters of the love of God.",
      "And, for many years more, she poured out these waters for the glory of the Cause she loved so well."
    ]
  },
  {
    id: "tahirih",
    theme: "courage",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Ṭáhirih",
    sourcePages: "section 69",
    sourceDetail: "From the Bahá'í Reference Library.",
    title: "Ṭáhirih, the Pure One.",
    quote: "Let deeds, not words, be our adorning!",
    readTime: "20 minute read",
    tags: ["Courage", "Learning", "Women", "Martyrdom", "Badasht"],
    summary:
      "The story of Ṭáhirih: her learning, recognition of the Báb, public teaching, Badasht, captivity, and martyrdom.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/6#992784946",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bah%C3%A1%27%C3%AD_gardens.jpg",
    featureImageAlt: "Bahá'í gardens on Mount Carmel in Haifa",
    story: [
      "A woman chaste and holy, a sign and token of surpassing beauty, a burning brand of the love of God, a lamp of His bestowal, was Jináb-i-Ṭáhirih. She was called Umm-Salmá; she was the daughter of Ḥájí Mullá Ṣáliḥ, a mujtahid of Qazvín, and her paternal uncle was Mullá Taqí, the Imám-Jum‘ih or leader of prayers in the cathedral mosque of that city. They married her to Mullá Muḥammad, the son of Mullá Taqí, and she gave birth to three children, two sons and a daughter; all three were bereft of the grace that encompassed their mother, and all failed to recognize the truth of the Cause.",
      "When she was still a child her father selected a teacher for her and she studied various branches of knowledge and the arts, achieving remarkable ability in literary pursuits. Such was the degree of her scholarship and attainments that her father would often express his regret, saying, “Would that she had been a boy, for he would have shed illumination upon my household, and would have succeeded me!”",
      "One day she was a guest in the home of Mullá Javád, a cousin on her mother’s side, and there in her cousin’s library she came upon some of the writings of Shaykh Aḥmad-i-Aḥsá’í. Delighted with what he had to say, Ṭáhirih asked to borrow the writings and take them home. Mullá Javád violently objected, telling her: “Your father is an enemy of the Twin Luminous Lights, Shaykh Aḥmad and Siyyid Káẓim. If he should even dream that any words of those two great beings, any fragrance from the garden of those realities, had come your way, he would make an attempt against my life, and you too would become the target of his wrath.” Ṭáhirih answered: “For a long time now, I have thirsted after this; I have yearned for these explanations, these inner truths. Give me whatever you have of these books. Never mind if it angers my father.” Accordingly, Mullá Javád sent over the writings of the Shaykh and the Siyyid.",
      "One night, Ṭáhirih sought out her father in his library, and began to speak of Shaykh Aḥmad’s teachings. The very moment he learned that his daughter knew of the Shaykhí doctrines, Mullá Ṣáliḥ’s denunciations rang out, and he cried: “Javád has made you a lost soul!” Ṭáhirih answered, “The late Shaykh was a true scholar of God, and I have learned an infinity of spiritual truths from reading his books. Furthermore, he bases whatever he says on the traditions of the Holy Imáms. You call yourself a mystic knower and a man of God, you consider your respected uncle to be a scholar as well, and most pious—yet in neither of you do I find a trace of those qualities!”",
      "For some time, she carried on heated discussions with her father, debating such questions as the Resurrection and the Day of Judgment, the Night-Ascent of Muḥammad to Heaven, the Promise and the Threat, and the Advent of the Promised One. Lacking arguments, her father would resort to curses and abuse. Then one night, in support of her contention, Ṭáhirih quoted a holy tradition from the Imám Ja‘far-i-Ṣádiq; and since it confirmed what she was saying, her father burst out laughing, mocking the tradition. Ṭáhirih said, “Oh my father, these are the words of the Holy Imám. How can you mock and deny them?”",
      "From that time on, she ceased to debate and contend with her father. Meanwhile she entered into secret correspondence with Siyyid Káẓim, regarding the solution of complex theological problems, and thus it came about that the Siyyid conferred on her the name “Solace of the Eyes” (Qurratu’l-‘Ayn); as for the title Ṭáhirih (“The Pure One”), it was first associated with her in Badasht, and was subsequently approved by the Báb, and recorded in Tablets.",
      "Ṭáhirih had caught fire. She set out for Karbilá, hoping to meet Siyyid Káẓim, but she arrived too late: ten days before she reached that city, he passed away. Not long before his death the Siyyid had shared with his disciples the good news that the promised Advent was at hand. “Go forth,” he repeatedly told them, “and seek out your Lord.” Thus the most distinguished of his followers gathered for retirement and prayer, for fasts and vigils, in the Masjid-i-Kúfih, while some awaited the Advent in Karbilá. Among these was Ṭáhirih, fasting by day, practicing religious disciplines, and spending the night in vigils, and chanting prayers. One night when it was getting along toward dawn she laid her head on her pillow, lost all awareness of this earthly life, and dreamed a dream; in her vision a youth, a Siyyid, wearing a black cloak and a green turban, appeared to her in the heavens; he was standing in the air, reciting verses and praying with his hands upraised. At once, she memorized one of those verses, and wrote it down in her notebook when she awoke. After the Báb had declared His mission, and His first book, “The Best of Stories,” was circulated, Ṭáhirih was reading a section of the text one day, and she came upon that same verse, which she had noted down from the dream. Instantly offering thanks, she fell to her knees and bowed her forehead to the ground, convinced that the Báb’s message was truth.",
      "This good news reached her in Karbilá and she at once began to teach. She translated and expounded “The Best of Stories,” also writing in Persian and Arabic, composing odes and lyrics, and humbly practicing her devotions, performing even those that were optional and supernumerary. When the evil ‘ulamás in Karbilá got wind of all this, and learned that a woman was summoning the people to a new religion and had already influenced a considerable number, they went to the Governor and lodged a complaint. Their charges, to be brief, led to violent attacks on Ṭáhirih, and sufferings, which she accepted and for which she offered praise and thanks. When the authorities came hunting for her they first assaulted Shamsu’ḍ-Ḍuḥá, mistaking her for Ṭáhirih. As soon, however, as they heard that Ṭáhirih had been arrested they let Shams go—for Ṭáhirih had sent a message to the Governor saying, “I am at your disposal. Do not harm any other.”",
      "The Governor set guards over her house and shut her away, writing Baghdad for instructions as to how he should proceed. For three months, she lived in a state of siege, completely isolated, with the guards surrounding her house. Since the local authorities had still received no reply from Baghdad, Ṭáhirih referred her case to the Governor, saying: “No word has come from either Baghdad or Constantinople. Accordingly, we will ourselves proceed to Baghdad and await the answer there.” The Governor gave her leave to go, and she set out, accompanied by Shamsu’ḍ-Ḍuḥá and the Leaf of Paradise (the sister of Mullá Ḥusayn) and her mother. In Baghdad she stayed first in the house of Shaykh Muḥammad, the distinguished father of Áqá Muḥammad-Muṣṭafá. But so great was the press of people around her that she transferred her residence to another quarter, engaged night and day in spreading the Faith, and freely associated with the inhabitants of Baghdad. She thus became celebrated throughout the city and there was a great uproar.",
      "Ṭáhirih also maintained a correspondence with the ‘ulamás of Káẓimayn; she presented them with unanswerable proofs, and when one or another appeared before her she offered him convincing arguments. Finally she sent a message to the Shí‘ih divines, saying to them: “If you are not satisfied with these conclusive proofs, I challenge you to a trial by ordeal.” Then there was a great outcry from the divines, and the Governor was obliged to send Ṭáhirih and her women companions to the house of Ibn-i-Álúsí, who was muftí of Baghdad. Here she remained about three months, waiting for word and directions from Constantinople. Ibn-i-Álúsí would engage her in learned dialogues, questions would be asked and answers given, and he would not deny what she had to say.",
      "On a certain day the muftí related one of his dreams, and asked her to tell him what it meant. He said: “In my dream I saw the Shí‘ih ‘ulamás arriving at the holy tomb of Imám Ḥusayn, the Prince of Martyrs. They took away the barrier that encloses the tomb, and they broke open the resplendent grave, so that the immaculate body lay revealed to their gaze. They sought to take up the holy form, but I cast myself down on the corpse and I warded them off.” Ṭáhirih answered: “This is the meaning of your dream: you are about to deliver me from the hands of the Shí‘ih divines.” “I too had interpreted it thus,” said Ibn-i-Álúsí.",
      "Since he had discovered that she was well versed in learned questions and in sacred commentaries and Texts, the two often carried on debates; she would speak on such themes as the Day of Resurrection, the Balance, and the Ṣiráṭ, and he would not turn away.",
      "Then came a night when the father of Ibn-i-Álúsí called at the house of his son. He had a meeting with Ṭáhirih and abruptly, without asking a single question, began to curse, mock and revile her. Embarrassed at his father’s behavior, Ibn-i-Álúsí apologized. Then he said: “The answer has come from Constantinople. The King has commanded that you be set free, but only on condition that you leave his realms. Go then, tomorrow, make your preparations for the journey, and hasten away from this land.”",
      "Accordingly Ṭáhirih, with her women companions, left the muftí’s house, saw to arranging for their travel gear, and went out of Baghdad. When they left the city, a number of Arab believers, carrying arms, walked along beside their convoy. Among the escort were Shaykh Sulṭán, Shaykh Muḥammad and his distinguished son Muḥammad-Muṣṭafá, and Shaykh Ṣáliḥ, and these were mounted. It was Shaykh Muḥammad who defrayed the expenses of the journey.",
      "When they reached Kirmánsháh the women alighted at one house, the men at another, and the inhabitants arrived in a continuous stream to seek information as to the new Faith. Here as elsewhere the ‘ulamás were soon in a state of frenzy and they commanded that the newcomers be expelled. As a result the kad-khudá or chief officer of that quarter, with a band of people, laid siege to the house where Ṭáhirih was, and sacked it. Then they placed Ṭáhirih and her companions in an uncovered howdah and carried them from the town to an open field, where they put the captives out. The drivers then took their animals and returned to the city. The victims were left on the bare ground, with no food, no shelter, and no means of traveling on.",
      "Ṭáhirih at once wrote a letter to the prince of that territory, in which she told him: “O thou just Governor! We were guests in your city. Is this the way you treat your guests?” When her letter was brought to the Governor of Kirmánsháh he said: “I knew nothing of this injustice. This mischief was kindled by the divines.” He immediately commanded the kad-khudá to return all the travelers’ belongings. That official duly surrendered the stolen goods, the drivers with their animals came back out of the city, the travelers took their places and resumed the journey.",
      "They arrived in Hamadán and here their stay was a happy one. The most illustrious ladies of that city, even the princesses, would come to visit, seeking the benefits of Ṭáhirih’s teaching. In Hamadán she dismissed a part of her escort and sent them back to Baghdad, while she brought some of them, including Shamsu’ḍ-Ḍuḥá and Shaykh-Ṣáliḥ, along with her to Qazvín.",
      "As they traveled, some riders advanced to meet them, kinsmen of Ṭáhirih’s from Qazvín, and they wished to lead her away alone, unescorted by the others, to her father’s house. Ṭáhirih refused, saying: “These are in my company.” In this way they entered Qazvín. Ṭáhirih proceeded to her father’s house, while the Arabs who had formed her escort alighted at a caravanserai. Ṭáhirih soon left her father and went to live with her brother, and there the great ladies of the city would come to visit her; all this until the murder of Mullá Taqí, when every Bábí in Qazvín was taken prisoner. Some were sent to Ṭihrán and then returned to Qazvín and martyred.",
      "Mullá Taqí’s murder came about in this way: One day, when that besotted tyrant had mounted his pulpit, he began to mock and revile the great Shaykh Aḥmad-i-Aḥsá’í. Shamelessly, grossly, screaming obscenities, he cried out: “That Shaykh is the one who has kindled this fire of evil, and subjected the whole world to this ordeal!” There was an inquirer in the audience, a native of Shíráz. He found the taunts, jeers and indecencies to be more than he could bear. Under cover of darkness he betook himself to the mosque, plunged a spearhead between the lips of Mullá Taqí and fled. The next morning they arrested the defenseless believers and thereupon subjected them to agonizing torture, though all were innocent and knew nothing of what had come to pass. There was never any question of investigating the case; the believers repeatedly declared their innocence but no one paid them any heed. When a few days had passed the killer gave himself up; he confessed to the authorities, informing them that he had committed the murder because Mullá Taqí had vilified Shaykh Aḥmad. “I deliver myself into your hands,” he told them, “so that you will set these innocent people free.” They arrested him as well, put him in the stocks, chained him, and sent him in chains, along with the others, to Ṭihrán.",
      "Once there he observed that despite his confession, the others were not released. By night, he made his escape from the prison and went to the house of Riḍá Khán—that rare and precious man, that star-sacrifice among the lovers of God—the son of Muḥammad Khán, Master of the Horse to Muḥammad Sháh. He stayed there for a time, after which he and Riḍá Khán secretly rode away to the Fort of Shaykh Ṭabarsí in Mázindarán. Muḥammad Khán sent riders after them to track them down, but try as they might, no one could find them. Those two horsemen got to the Fort of Ṭabarsí, where both of them won a martyr’s death. As for the other friends who were in the prison at Ṭihrán, some of these were returned to Qazvín and they too suffered martyrdom.",
      "One day the administrator of finance, Mírzá Shafí‘, called in the murderer and addressed him, saying: “Jináb, do you belong to a dervish order, or do you follow the Law? If you are a follower of the Law, why did you deal that learned mujtahid a cruel, a fatal blow in the mouth? If you are a dervish and follow the Path, one of the rules of the Path is to harm no man. How, then, could you slaughter that zealous divine?” “Sir,” he replied, “besides the Law, and besides the Path, we also have the Truth. It was in serving the Truth that I paid him for his deed.”",
      "These things would take place before the reality of this Cause was revealed and all was made plain. For in those days no one knew that the Manifestation of the Báb would culminate in the Manifestation of the Blessed Beauty and that the law of retaliation would be done away with, and the foundation-principle of the Law of God would be this, that “It is better for you to be killed than to kill”; that discord and contention would cease, and the rule of war and butchery would fall away. In those days, that sort of thing would happen. But praised be God, with the advent of the Blessed Beauty such a splendor of harmony and peace shone forth, such a spirit of meekness and long-suffering, that when in Yazd men, women and children were made the targets of enemy fire or were put to the sword, when the leaders and the evil ‘ulamás and their followers joined together and unitedly assaulted those defenseless victims and spilled out their blood—hacking at and rending apart the bodies of chaste women, with their daggers slashing the throats of children they had orphaned, then setting the torn and mangled limbs on fire—not one of the friends of God lifted a hand against them. Indeed, among those martyrs, those real companions of the ones who died, long gone, at Karbilá, was a man who, when he saw the drawn sword flashing over him, thrust sugar candy into his murderer’s mouth and cried, “With a sweet taste on your lips, put me to death—for you bring me martyrdom, my dearest wish!”",
      "Let us return to our theme. After the murder of her impious uncle, Mullá Taqí, in Qazvín, Ṭáhirih fell into dire straits. She was a prisoner and heavy of heart, grieving over the painful events that had come to pass. She was watched on every side, by attendants, guards, the farráshes, and her foes. While she languished thus, Bahá’u’lláh dispatched Hádíy-i-Qazvíní, husband of the celebrated Khátún-Ján, from the capital, and they managed, by a stratagem, to free her from that embroilment and got her to Ṭihrán in the night. She alighted at the mansion of Bahá’u’lláh and was lodged in an upper apartment.",
      "When word of this spread throughout Ṭihrán, the Government hunted for her high and low; nevertheless, the friends kept arriving to see her, in a steady stream, and Ṭáhirih, seated behind a curtain, would converse with them. One day the great Siyyid Yaḥyá, surnamed Vaḥíd, was present there. As he sat without, Ṭáhirih listened to him from behind the veil. I was then a child, and was sitting on her lap. With eloquence and fervor, Vaḥíd was discoursing on the signs and verses that bore witness to the advent of the new Manifestation. She suddenly interrupted him and, raising her voice, vehemently declared: “O Yaḥyá! Let deeds, not words, testify to thy faith, if thou art a man of true learning. Cease idly repeating the traditions of the past, for the day of service, of steadfast action, is come. Now is the time to show forth the true signs of God, to rend asunder the veils of idle fancy, to promote the Word of God, and to sacrifice ourselves in His path. Let deeds, not words, be our adorning!”",
      "The Blessed Beauty made elaborate arrangements for Ṭáhirih’s journey to Badasht and sent her off with an equipage and retinue. His own party left for that region some days afterward.",
      "In Badasht, there was a great open field. Through its center a stream flowed, and to its right, left, and rear there were three gardens, the envy of Paradise. One of those gardens was assigned to Quddús, but this was kept a secret. Another was set apart for Ṭáhirih, and in a third was raised the pavilion of Bahá’u’lláh. On the field amidst the three gardens, the believers pitched their tents. Evenings, Bahá’u’lláh, Quddús and Ṭáhirih would come together. In those days the fact that the Báb was the Qá’im had not yet been proclaimed; it was the Blessed Beauty, with Quddús, Who arranged for the proclamation of a universal Advent and the abrogation and repudiation of the ancient laws.",
      "Then one day, and there was a wisdom in it, Bahá’u’lláh fell ill; that is, the indisposition was to serve a vital purpose. On a sudden, in the sight of all, Quddús came out of his garden, and entered the pavilion of Bahá’u’lláh. But Ṭáhirih sent him a message, to say that their Host being ill, Quddús should visit her garden instead. His answer was: “This garden is preferable. Come, then, to this one.” Ṭáhirih, with her face unveiled, stepped from her garden, advancing to the pavilion of Bahá’u’lláh; and as she came, she shouted aloud these words: “The Trumpet is sounding! The great Trump is blown! The universal Advent is now proclaimed!” The believers gathered in that tent were panic struck, and each one asked himself, “How can the Law be abrogated? How is it that this woman stands here without her veil?”",
      "“Read the Súrih of the Inevitable,” said Bahá’u’lláh; and the reader began: “When the Day that must come shall have come suddenly… Day that shall abase! Day that shall exalt!…” and thus was the new Dispensation announced and the great Resurrection made manifest. At the start, those who were present fled away, and some forsook their Faith, while some fell a prey to suspicion and doubt, and a number, after wavering, returned to the presence of Bahá’u’lláh. The Conference of Badasht broke up, but the universal Advent had been proclaimed.",
      "Afterward, Quddús hastened away to the Fort of Ṭabarsí and the Blessed Beauty, with provisions and equipment, journeyed to Níyálá, having the intention of going on from there by night, making His way through the enemy encampment and entering the Fort. But Mírzá Taqí, the Governor of Ámul, got word of this, and with seven hundred riflemen arrived in Níyálá. Surrounding the village by night, he sent Bahá’u’lláh with eleven riders back to Ámul, and those calamities and tribulations, told of before, came to pass.",
      "As for Ṭáhirih, after the breakup at Badasht she was captured, and the oppressors sent her back under guard to Ṭihrán. There she was imprisoned in the house of Maḥmúd Khán, the Kalántar. But she was aflame, enamored, restless, and could not be still. The ladies of Ṭihrán, on one pretext or another, crowded to see and listen to her. It happened that there was a celebration at the Mayor’s house for the marriage of his son; a nuptial banquet was prepared, and the house adorned. The flower of Ṭihrán’s ladies were invited, the princesses, the wives of vazírs and other great. A splendid wedding it was, with instrumental music and vocal melodies—by day and night the lute, the bells and songs. Then Ṭáhirih began to speak; and so bewitched were the great ladies that they forsook the cithern and the drum and all the pleasures of the wedding feast, to crowd about Ṭáhirih and listen to the sweet words of her mouth.",
      "Thus she remained, a helpless captive. Then came the attempt on the life of the Sháh; a farmán was issued; she was sentenced to death. Saying she was summoned to the Prime Minister’s, they arrived to lead her away from the Kalántar’s house. She bathed her face and hands, arrayed herself in a costly dress, and scented with attar of roses she came out of the house.",
      "They brought her into a garden, where the headsmen waited; but these wavered and then refused to end her life. A slave was found, far gone in drunkenness; besotted, vicious, black of heart. And he strangled Ṭáhirih. He forced a scarf between her lips and rammed it down her throat. Then they lifted up her unsullied body and flung it in a well, there in the garden, and over it threw down earth and stones. But Ṭáhirih rejoiced; she had heard with a light heart the tidings of her martyrdom; she set her eyes on the supernal Kingdom and offered up her life.",
      "Salutations be unto her, and praise. Holy be her dust, as the tiers of light come down on it from Heaven."
    ]
  },
  {
    id: "harry-randall-guidance",
    theme: "guidance",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Guidance",
    sourcePages: "p. 24",
    sourceDetail: "From Bahá'í Stories.",
    title: "Harry Randall follows guidance.",
    quote: "John, John he's come!",
    readTime: "3 minute read",
    tags: ["Guidance", "Teaching", "Dreams", "Trust", "Search"],
    summary:
      "Harry Randall prays at each crossing until a long walk brings him to the door of someone already waiting.",
    source: "https://bahaistories.com/subject/intuition",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bahai_Gardens_Haifa.jpg",
    featureImageAlt: "Terraces and gardens near the Shrine of the Báb in Haifa",
    story: [
      "Harry Randall, once he had leaped the hurdle and become a Bahá’í was a very enthusiastic one. When Harlan told him about 'guidance' - what a mystery it was, and how earnestly Harlan himself was trying to understand and live under it Harry, too, began to try to apply it. One afternoon he started out to take a walk and, in an effort to understand this guidance that Harlan talked about, Harry paused at each cross street and corner praying that he might be urged in whatever direction it might be that God wished him to take. He walked and walked, the city streets gave way to country roads and still he walked. At some corners he was moved to turn; at some he went straight ahead. But he felt no urge to stop he felt strongly that he should keep going. Finally, at the end of the afternoon, he came to a small white house surrounded by a picket fence - and here, with his hand on the gate, he knew this was the house he had been led to; this was the end of his walk. So he opened the gate, went up the short path and knocked at the door. A woman opened the door and, giving him one look, called back over her shoulder, 'John, John he's come!'  It seems that the night before, this woman had had a dream in which she had gone to open her door to one who knocked - a man who had come into her house and told her something that was so exciting and wonderful that when she woke up - though she couldn't remember what the exciting and wonderful thing had been - she was still so excited she'd told her husband about it. And then Harry had knocked - Harry had come into her house and Harry had told her about Bahá’u’lláh and given her the wonderful Message for the New Day."
    ]
  },
  {
    id: "mishkin-qalam",
    theme: "courage",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Mishkín-Qalam",
    sourcePages: "section 38",
    sourceDetail: "From the Bahá'í Reference Library.",
    title: "Mishkín-Qalam.",
    quote: "he feared no one but God",
    readTime: "6 minute read",
    tags: ["Courage", "Art", "Teaching", "Steadfastness", "Exile"],
    summary:
      "The complete memorial of Mishkín-Qalam, calligrapher, exile, and faithful companion.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/4#604886557",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Shrine_of_Bah%C3%A1%27u%27ll%C3%A1h.jpg",
    featureImageAlt: "The Shrine of Bahá'u'lláh near Bahjí",
    story: [
      "Among the exiles, neighbors, and prisoners there was also a second Mír ‘Imád, the eminent calligrapher, Mishkín-Qalam. He wielded a musk-black pen, and his brows shone with faith. He was among the most noted of mystics, and had a witty and subtle mind. The fame of this spiritual wayfarer reached out to every land. He was the leading calligrapher of Persia and well known to all the great; he enjoyed a special position among the court ministers of Ṭihrán, and with them he was solidly established. He was famed throughout Asia Minor; his pen was the wonder of all calligraphers, for he was adept at every calligraphic style. He was besides, for human virtues, a bright star.",
      "This highly accomplished man first heard of the Cause of God in Iṣfahán, and the result was that he set out to find Bahá’u’lláh. He crossed the great distances, measured out the miles, climbing mountains, passing over deserts and over the sea, until at last he came to Adrianople. Here he reached the heights of faith and assurance; here he drank the wine of certitude. He responded to the summons of God, he attained the presence of Bahá’u’lláh, he ascended to that apogee where he was received and accepted. By now he was reeling to and fro like a drunkard in his love for God, and because of his violent desire and yearning, his mind seemed to wander. He would be raised up, and then cast down again; he was as one distracted. He spent some time under the sheltering grace of Bahá’u’lláh, and every day new blessings were showered upon him. Meanwhile he produced his splendid calligraphs; he would write out the Most Great Name, Yá Bahá’u’l-Abhá, O Thou Glory of the All-Glorious, with marvelous skill, in many different forms, and would send them everywhere.",
      "He was then directed to go on a journey to Constantinople, and set out with Jináb-i-Sayyáḥ. When he reached that Great City, the leading Persians and Turks received him with every honor at first, and they were captivated by his jet black, calligraphic art. He, however, began boldly and eloquently to teach the Faith. The Persian ambassador lurked in ambush; betaking himself to the Sulṭán’s vazírs he slandered Mishkín-Qalam. “This man is an agitator,” the ambassador told them, “sent here by Bahá’u’lláh to stir up trouble and make mischief in this Great City. He has already won over a large company, and he intends to subdue still more. These Bahá’ís turned Persia upside down; now they have started in on the capital of Turkey. The Persian Government put 20,000 of them to the sword, hoping by this tactic to quench the fires of sedition. You should awaken to the danger; soon this perverse thing will blaze up here as well. It will consume the harvest of your life; it will burn up the whole world. Then you can do nothing, for it will be too late.”",
      "Actually that mild and submissive man, in that throne city of Asia Minor, was occupied solely with his calligraphy and his worship of God. He was striving to bring about not sedition but fellowship and peace. He was seeking to reconcile the followers of different faiths, not to drive them still further apart. He was of service to strangers and was helping to educate the native people. He was a refuge to the hapless and a horn of plenty to the poor. He invited all comers to the oneness of humankind; he shunned hostility and malice.",
      "The Persian ambassador, however, wielded enormous power, and he had maintained close ties with the ministers for a very long time. He prevailed on a number of persons to insinuate themselves into various gatherings and there to make every kind of false charge against the believers. Urged on by the oppressors, spies began to surround Mishkín-Qalam. Then, as instructed by the ambassador, they carried reports to the Prime Minister, stating that the individual in question was stirring up mischief day and night, that he was a troublemaker, a rebel and a criminal. The result was, they jailed him and they sent him away to Gallipoli, where he joined our own company of victims. They despatched him to Cyprus and ourselves to the ‘Akká prison. On the island of Cyprus, Jináb-i-Mishkín was held prisoner in the citadel at Famagusta, and in this city he remained, a captive, from the year 85 till 94.",
      "When Cyprus passed out of Turkish hands, Mishkín-Qalam was freed and betook himself to his Well-Beloved in the city of ‘Akká, and here he lived encompassed by the grace of Bahá’u’lláh, producing his marvelous calligraphs and sending them about. He was at all times joyous of spirit, ashine with the love of God, like a candle burning its life away, and he was a consolation to all the believers.",
      "After the ascension of Bahá’u’lláh, Mishkín-Qalam remained loyal, solidly established in the Covenant. He stood before the violators like a brandished sword. He would never go half way with them; he feared no one but God; not for a moment did he falter, nor ever fail in service.",
      "Following the ascension he made a journey to India, where he associated with the lovers of truth. He spent some time there, making fresh efforts every day. When I learned that he was getting helpless, I sent for him at once and he came back to this Most Great Prison, to the joy of the believers, who felt blessed to have him here again. He was at all times my close companion. He had amazing verve, intense love. He was a compendium of perfections: believing, confident, serene, detached from the world, a peerless companion, a wit—and his character like a garden in full bloom. For the love of God, he left all good things behind; he closed his eyes to success, he wanted neither comfort nor rest, he sought no wealth, he wished only to be free from the defilement of the world. He had no ties to this life, but spent his days and nights supplicating and communing with God. He was always smiling, effervescing; he was spirit personified, love embodied. For sincerity and loyalty he had no match, nor for patience and inner calm. He was selflessness itself, living on the breaths of the spirit.",
      "If he had not been in love with the Blessed Beauty, if he had not set his heart on the Realm of Glory, every worldly pleasure could have been his. Wherever he went, his many calligraphic styles were a substantial capital, and his great accomplishment brought him attention and respect from rich and poor alike. But he was hopelessly enamored of man’s one true Love, and thus he was free of all those other bonds, and could float and soar in the spirit’s endless sky.",
      "Finally, when I was absent, he left this darksome, narrow world and hastened away to the land of lights. There, in the haven of God’s boundless mercy, he found infinite rewards. Unto him be praise and salutations, and the Supreme Companion’s tender grace."
    ]
  },
  {
    id: "offering-in-prayer",
    theme: "prayer",
    author: "Abu’l-Qasim Faizi",
    book: "Unsigned transcript of a talk by Hand of the Cause of God Abu’l-Qasim Faizi",
    chapter: "Our Offering in Prayer",
    sourcePages: "Melbourne, 26 November 1969",
    sourceDetail: "From Bahá'í Stories.",
    title: "Our offering in prayer.",
    quote: "Take your nothingness to Him.",
    readTime: "2 minute read",
    tags: ["Prayer", "Humility", "The Báb", "Nothingness", "Devotion"],
    summary:
      "Abu’l-Qasim Faizi tells how the Báb describes the one gift a soul can bring before God.",
    source: "https://bahaistories.com/subject/prayer",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lotus_Temple_in_New_Delhi_03-2016.jpg",
    featureImageAlt: "The Bahá'í House of Worship known as the Lotus Temple in New Delhi",
    story: [
      "Our Offering in Prayer",
      "“To me, many of the hard problems of all the religions of God have been explained by the Báb, very easily. He brought these things from heaven to earth, and said this is what it means…",
      "“Why do we pray? The Báb says, when we pray, what do we take to God? What do we talk to Him of, what do we offer Him? Do you offer your knowledge? He is the Source of knowledge. Do you offer Him your wealth? Do you offer Him your strength, the strength of body or mental strength? All these things are not even worthy of being mentioned in the sight of God.",
      "“Therefore, why do we pray? The Báb says, I will give you an example. Suppose you want to go and visit a king. You will go here and there and ask many people: what is it that the king does not have in his treasury? I would like to take it as a gift to him. And, for instance, suppose somebody will say if you take a moonstone, he does not have it, then you will take it.",
      "\"Now, if you take the whole treasure of the world, God has it. The whole knowledge of the world He is the source of it. Strength? He is the source of Power. But the Báb says, as I advise you and tell you, there is one thing that God does not have in His treasure house, and that is NOTHINGNESS. Take your nothingness to Him. When you sit down in front of Him and pray, have an attitude that you are nothing as compared with God. You take that attitude, and He says this will immediately be accepted.\""
    ]
  },
  {
    id: "ali-najaf-abadi",
    theme: "devotion",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "‘Alí Najaf-Ábádí",
    sourcePages: "p. 21",
    sourceDetail:
      "From the Bahá'í Reference Library. The stable source page is the Memorials page `/3`; the fetched page did not expose a per-entry anchor for this memorial.",
    title: "‘Alí Najaf-Ábádí.",
    quote: "he turned his eyes away from this world of dust",
    readTime: "2 minute read",
    tags: ["Devotion", "Pilgrimage", "Prayer", "Detachment", "Steadfastness"],
    summary:
      "A brief complete memorial of a quiet believer who journeyed, served, prayed, and died detached from the world.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/3",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Shrine_of_The_Bab.jpg",
    featureImageAlt: "The Shrine of the Báb and gardens in Haifa",
    story: [
      "Also among the emigrants and near neighbors was Áqá ‘Alí Najaf-Ábádí. When this spiritual young man first listened to the call of God he set his lips to the holy cup and beheld the glory of the Speaker on the Mount. And when, by grace of the light, he had attained positive knowledge, he journeyed to the Most Great Prison, where he witnessed the substance of knowledge itself, and arrived at the high station of indubitable truth.",
      "For a long time he remained in and about the sacred city; he became the proverbial Ḥabíbu’lláh the Merchant, and spent his days relying upon God, in supplication and prayer. He was a man meek, quiet, uncomplaining, steadfast; in all things pleasing, worthy of praise. He won the approval of all the friends and was accepted and welcome at the Holy Threshold. During his latter days, when he felt that a happy end was in store for him, he again presented himself at the holy city of the Most Great Prison.",
      "Upon arrival he fell ill, weakened, passed his hours in supplicating God. The breath of life ceased within him, the gates of flight to the supreme Kingdom were flung wide, he turned his eyes away from this world of dust and went onward to the Holy Place.",
      "‘Alí Najaf-Ábádí was tender and sensitive of heart, at all times mindful of God and remembering Him, and toward the close of his life detached, without stain, free from the contagion of this world. Sweetly, he gave up his corner of the earth, and pitched his tent in the land beyond. May God send upon him the pure savors of forgiveness, brighten his eyes with beholding the Divine Beauty in the Kingdom of Splendors, and refresh his spirit with the musk-scented winds that blow from the Abhá Realm.",
      "Unto him be salutation and praise. His sweet and holy dust lies in ‘Akká."
    ]
  },
  {
    id: "coal-miner-needs-no-translation",
    theme: "understanding",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Universal Language - heart to heart",
    sourcePages: "p. 38",
    sourceDetail:
      "From Bahá'í Stories. The subject page presents this full anecdote on-page without a per-story anchor.",
    title: "Anybody can understand Him.",
    quote: "Nothing ‘Abdu’l-Bahá says needs translating",
    readTime: "1 minute read",
    tags: ["Understanding", "Teaching", "Wonder", "Listening", "‘Abdu'l-Bahá"],
    summary:
      "A coal miner hears ‘Abdu’l-Bahá speak through an interpreter and insists the Master needs no translation.",
    source: "https://bahaistories.com/subject/universal-language-heart-heart",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Picture_of_Abdul-Baha.jpg",
    featureImageAlt: "A portrait photograph of ‘Abdu'l-Bahá",
    story: [
      "There is the story of the coal miner in California who had walked many miles to meet ‘Abdu’l-Bahá Who, of course spoke that evening as He always did through an interpreter. The coal miner became more and more impatient. Finally, unable to stand it any longer, he leaned toward the man sitting next to him. \"Why does that man continually interrupt the Master?\" he asked. The man explained, \"‘Abdu’l-Bahá is speaking in Persian it must, be translated.\" \"Translated!\" the coal miner was outraged.",
      "\"Nothing ‘Abdu’l-Bahá says needs translating - anybody can understand Him.\""
    ]
  },
  {
    id: "paul-haney-baby-insight",
    theme: "insight",
    author: "Agnes Parsons",
    book: "Agnes Parson’s Diary",
    chapter: "April 25, 1912",
    sourcePages: "April 25, 1912",
    sourceDetail:
      "From Bahá'í Stories. The subject page presents this diary excerpt on-page without a per-story anchor.",
    title: "The baby had seen more.",
    quote: "You have much insight.",
    readTime: "1 minute read",
    tags: ["Insight", "Children", "Wonder", "Pilgrimage", "‘Abdu'l-Bahá"],
    summary:
      "After a child cries on seeing ‘Abdu’l-Bahá, Agnes Parsons hears the Master confirm that the adults may have missed what the baby perceived.",
    source: "https://bahaistories.com/subject/hands-cause",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Baha%27i_House_of_Worship,_Kampala,_Uganda.jpg",
    featureImageAlt: "The Bahá'í House of Worship in Kampala, Uganda",
    story: [
      "Mr. and Mrs. Charles and Mariam Haney and the baby drove with ‘Abdu’l-Bahá in the morning. At the children’s meetings the baby [he was the future Hand of the Cause Mr. Paul Haney] had screamed when he saw ‘Abdu’l-Bahá and I thought at the time, that the child had probably been overwhelmed by seeing a greater spirituality in ‘Abdu’l-Bahá than many saw. Before they went to drive, I spoke of this to Mr. and Mrs. Haney, for the latter had shown such distress when it occurred. I believe Mr. Haney agreed with me. He said: “Three months before the child was born we were in Acca.” Afterward, when ‘Abdu’l-Bahá returned from the drive, I said to Him: “How was it with the baby?” “Everything was quite right” was His reply. I told Him I thought the baby had been conscious of more than we were, and ‘Abdu’l-Bahá’s answer was, “You have much insight.”"
    ]
  }
];
