window.ClaraStories = [
  {
    id: "sulayman-khan-tunukabani",
    theme: "teaching",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Sulaymán Khán-i-Tunukábání",
    sourcePages: "section 50",
    sourceDetail:
      "From the Bahá'í Reference Library; ‘Abdu'l-Bahá, Memorials of the Faithful, section 50.",
    title: "Sulaymán Khán-i-Tunukábání.",
    quote: "He became one of God’s farmers, scattering the holy seed of the Teachings.",
    readTime: "6 minute read",
    tags: ["Teaching", "Detachment", "India", "Service", "Steadfastness"],
    summary:
      "A complete memorial of Jamáli’d-Dín, who left rank behind, carried hope to India, and later delivered a letter of promised restoration.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/5",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/House_of_Abbud.jpg",
    featureImageAlt: "The House of 'Abbúd in Acre, where Bahá'u'lláh lived",
    addedOn: "2026-05-01",
    featuredOn: "2026-05-01",
    story: [
      "Sulaymán Khán was the emigrant and settler who was given the title of Jamáli’d-Dín. He was born in Tunukábán, into an old family of that region. He was cradled in wealth, bred to ease, reared in the comfortable ways of luxury. From his early childhood he had high ambitions and noble aims, and he was honor and aspiration personified. At first he planned to outdistance all his fellows and achieve some lofty rank.",
      "For this reason he left his birthplace and went to the capital, Ṭihrán, where he hoped to become a leader, surpassing the rest of his generation.",
      "In Ṭihrán, however, the fragrance of God was borne his way, and he listened to the summons of the Well-Beloved. He was saved from the perturbations of high rank; from all the din and clatter, the glory, the pomps and palaces, of this heap of dust, the world. He threw off his chains, and by God’s grace, discovered peace. To him, the seat of honor was now no different from the place where people removed their slippers at the door, and high office was a thing soon gone and forgotten.",
      "He was cleansed from the stain of living, his heart was eased, for he had burst the shackles that held him to this present life.",
      "Putting on the garments of a pilgrim, he set out to find his loving Friend, and came to the Most Great Prison. Here for a time he rested, under the protection of the Ancient Beauty; here he gained the honor of entering the presence of Bahá’u’lláh, and listened to momentous teachings from His holy lips.",
      "When he had breathed the scented air, when his eyes were illumined and his ears attuned to the words of the Lord, he was permitted to make a journey to India, and bidden to teach the true seekers after truth.",
      "Resting his heart on God, in love with the sweet savors of God, on fire with the love of God, he left for India. There he wandered, and whenever he came to a city he raised the call of the Great Kingdom and delivered the good news that the Speaker of the Mount had come. He became one of God’s farmers, scattering the holy seed of the Teachings. This sowing was fruitful. Through him a considerable number found their way into the Ark of Salvation.",
      "The light of Divine guidance was shed upon those souls, and their eyes were brightened with beholding the mighty signs of God. He became the focal point of every gathering, the honored guest. To this day, in India, the results of his auspicious presence are clear to see, and those whom he taught are now, in their turn, guiding others to the Faith.",
      "Following his Indian journey, Sulaymán Khán came back to Bahá’u’lláh, but when he arrived, the ascension had taken place. Continuously, he shed his tears, and his heart was a thurible for sorrow. But he remained loyal to the Covenant, well rooted in Heaven.",
      "Not long before His passing, Bahá’u’lláh had said: “Should someone go to Persia, and manage to convey it, this message must be delivered to Amínu’s-Sulṭán: ‘You took steps to help the prisoners; you freely rendered them a befitting service; this service will not be forgotten. Rest assured that it will bring you honor and call down a blessing upon all your affairs.",
      "O Amínu’s-Sulṭán! Every house that is raised up will one day fall to ruin, except the house of God; that will grow more massive and be better guarded day by day. Then serve the Court of God with all your might, that you may discover the way to a home in Heaven, and found an edifice that will endure forever.’” After the departure of Bahá’u’lláh, this message was conveyed to Amínu’s-Sulṭán.",
      "In Á dh irbáyján the Turkish clerics had brought down Áqá Siyyid Asadu’lláh, hunted him down in Ardabíl and plotted to shed his blood; but the Governor, by a ruse, managed to save him from being physically beaten and then murdered: he sent the victim to Tabríz in chains, and from there had him conducted to Ṭihrán. Amínu’s-Sulṭán came to the prisoner’s assistance and, in his own office, provided Asadu’lláh with a sanctuary. One day when the Prime Minister was ill, Náṣiri’d-Dín Sh áh arrived to visit him.",
      "The Minister then explained the situation, and lavished praise upon his captive; so much so that the Sh áh, as he left, showed great kindness to Asadu’lláh, and spoke words of consolation. This, when at an earlier time, the captive would have been strung up at once to adorn some gallows-tree, and shot down with a gun.",
      "After a time Amínu’s-Sulṭán lost the Sovereign’s favor. Hated, in disgrace, he was banished to the city of Qum. Thereupon this servant dispatched Sulaymán Khán to Persia, carrying a prayer and a missive written by me. The prayer besought God’s aid and bounty and succor for the fallen Minister, so that he might, from that corner of oblivion, be recalled to favor. In the letter we clearly stated: “Prepare to return to Ṭihrán.",
      "Soon will God’s help arrive; the light of grace will shine on you again; with full authority again, you will find yourself free, and Prime Minister. This is your reward for the efforts you exerted on behalf of a man who was oppressed.” That letter and that prayer are today in the possession of the family of Amínu’s-Sulṭán.",
      "From Ṭihrán, Sulaymán Khán journeyed to Qum, and according to his instructions went to live in a cell in the shrine of the Immaculate. The relatives of Amínu’s-Sulṭán came to visit there; Sulaymán Khán inquired after the fallen Minister and expressed the wish to meet him. When the Minister learned of this, he sent for Sulaymán Khán. Placing all his trust in God, Sulaymán Khán hastened to the Minister’s house and, meeting him in private, presented the letter from ‘Abdu’l‑Bahá.",
      "The Minister rose, and received the letter with extreme respect. Then addressing the Khán he said: “I had given up hope. If this longing is fulfilled, I will arise to serve; I will preserve and uphold the friends of God.” Then he expressed his gratitude, indebtedness and joy, and added, “Praise be to God, I hope again; I feel that by His aid, my dream will come true.”",
      "In brief, the Minister pledged himself to serve the friends, and Sulaymán Khán took his leave. The Minister then desired to give him a sum of money to defray the expenses of his journey, but Sulaymán Khán refused, and despite the Minister’s insistence, would accept nothing. The Khán had not yet reached the Holy Land on his return journey when Amínu’s-Sulṭán was recalled from exile and immediately summoned to the Premiership again.",
      "He assumed the position and functioned with full authority; and at first he did indeed support the believers, but toward the end, in the case of the Yazd martyrdoms, he was neglectful. He neither helped nor protected the sufferers in any way, nor would he listen to their repeated pleas, until all of them were put to death. Accordingly he too was dismissed, a ruined man; that flag which had flown so proudly was reversed, and that hoping heart despaired.",
      "Sulaymán Khán lived on in the Holy Land, near the Shrine which the Exalted Assembly circle about. He kept company with the believers until the day of inescapable death, when he set out for the mansions of Him Who liveth, and dieth not. He turned his back on this heap of dust, the world, and hurried away to the country of light. He broke out of this cage of contingent being and soared into the endless, placeless Realm.",
      "May God enfold him in the waters of His mercy, cause His forgiveness to rain down upon him, and bestow on him the wonders of abounding grace. Salutations be unto him, and praise."
    ]
  },
  {
    id: "corn-for-the-british-army",
    theme: "service",
    author: "Lady Blomfield",
    book: "The Chosen Highway",
    chapter: "Planning",
    sourceDetail:
      "From Bahá'í Stories; Lady Blomfield, The Chosen Highway.",
    title: "‘Abdu’l-Bahá had prepared for the famine.",
    quote: "I have corn for the British Army,",
    readTime: "2 minute read",
    tags: ["Service", "Foresight", "Haifa", "Generosity", "War"],
    collectionTags: ["Anecdotes"],
    summary:
      "A wartime account of ‘Abdu’l-Bahá's foresight in storing grain for civilians and even for the arriving British Army.",
    source: "https://bahaistories.com/subject/planning",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Shrine_of_the_B%C3%A1b_-_Haifa.jpg",
    featureImageAlt: "The Shrine of the Báb and its terraces in Haifa",
    addedOn: "2026-04-30",
    story: [
      "Preparation for war conditions had been made by ‘Abdu’l-Bahá even before His return to Palestine, after His world tour. The people of the villages Nughayb, Samrih, and 'Adasiyyih were instructed by the Master how to grow corn, so as to produce prolific harvests, in the period before and during the lean years of the war. A vast quantity of this corn was stored in pits, some of which had been made by the Romans, and were now utilized for this purpose.",
      "So it came about that ‘Abdu’l-Bahá was able to feed numberless poor of the people of Haifa, 'Akká, and the neighbourhood, in the famine years of 1914-1918.",
      "We learned that when the British marched into Haifa there was some difficulty about the commissariat. The officer in command went to consult the Master.",
      "\"I have corn,\" was the reply.",
      "\"But for the army?\" said the astonished soldier.",
      "\"I have corn for the British Army,\" said ‘Abdu’l-Bahá.",
      "He truly walked the Mystic way with practical feet. Lady Blomfield often recounted how the corn pits proved a safe hiding-place for the corn, during the occupation of the Turkish army.",
      "When the British arrived in Haifa, where the blockade had caused a perilous condition for the inhabitants, it was discovered that ‘Abdu’l-Bahá had saved the civilian population from starvation. Provisions which He had grown, buried in under-ground pits, and otherwise stored, had been given out to the civilians of every nation living in Haifa.",
      "‘Abdu’l-Bahá did this in a military way as an army would give rations, and deep was the gratitude of those women and children who had been saved by His power to see into the future of tragedy and woe as early as 1912, when He began the preparations for the catastrophe which was to overtake that land in 1917 and 1918. When Haifa was finally occupied by the British, reserve provisions had not yet come for the army, and someone in authority approached the Master, as already mentioned.",
      "The British Government, with its usual gesture of appreciating a heroic act, conferred a knighthood upon ‘Abdu’l-Bahá 'Abbas, Who accepted this honour as a courteous gift \"from a just king.\""
    ]
  },
  {
    id: "grace-obers-first-small-step",
    theme: "service",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Service",
    sourcePages: "pp. 17-19",
    sourceDetail:
      "From Bahá'í Stories; Reginald Grant Barrow, Mother's Stories, pp. 17-19.",
    title: "Grace learns what service means.",
    quote: "Are you as happy scrubbing the garbage pails as you are arranging the roses?",
    readTime: "8 minute read",
    tags: ["Service", "Humility", "Detachment", "Household", "New York"],
    summary:
      "Grace Robarts Ober asks to serve ‘Abdu'l-Bahá and learns, through a difficult hidden test, what selfless joy in service really means.",
    source: "https://bahaistories.com/subject/service",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/AAbdul-baha_late_life.jpg",
    featureImageAlt: "‘Abdu'l-Bahá seated outdoors with believers in His later life",
    addedOn: "2026-04-30",
    featuredOn: "2026-04-30",
    story: [
      "There are many stories about beloved Grace Robarts Ober who, for so very many years, dedicated every moment of her life to the service of our glorious Cause. And this experience, she felt, was the 'first small step' - to use her words, that set her feet on the path. Grace had been introduced to the Cause by that early dedicated soul, Lua Getzinger, and Grace had, at once, recognized Bahá’u’lláh and become a Bahá’í. Not long afterward, Lua came to Grace and told her that very soon ‘Abdu’l-Bahá was to arrive in New York and she, Lua, had been asked by Him to go to Chicago and prepare a place there in which he might stay when he arrived in that city. Would Grace like to go to Chicago with Lua and help with this preparation? Of course Grace would! So, together, they went to Chicago from Los Angeles, found a suitable apartment, prepared it and, eventually, ‘Abdu’l-Bahá came to live in it. When His stay in Chicago was nearly over, suddenly one morning Grace realized what it would mean to go back to the dead stuffiness of her former life and leave this clear and radiant glory in which she'd been living while she helped Lua keep house for the Master. So she went to ‘Abdu’l-Bahá and begged that, when he returned to New York, she might help with that household too, as she had been privileged to do in Chicago. ‘Abdu’l-Bahá looked at her very searchingly and said, \"Greece (His loving nickname for Grace) Greece, are you SURE you wish to serve ME?\" Grace said, with great enthusiasm, \"Oh, YES! More than anything else in the world!\" ‘Abdu’l-Bahá made no answer but walked away. The next morning this scene was repeated. On the third morning, Grace, frantic at the realization that this was the last morning before He was leaving to go farther West, went to Him a third time - and this time He became very stern. Are you VERY SURE you wish to SERVE ME? Grace was startled at the sternness but she didn't waver. \"YES I am VERY SURE.\" So then he nodded. \"Very well go, settle up your affairs, and we will meet in New York.\" Jubilant and radiant, Grace settled up her 'affairs' - which consisted of subletting a cottage she had taken at Greenacre for the summer and doing a few other things. Then, with wings on her feet, she went to New York. Lua was already there and together they prepared for ‘Abdu’l-Bahá’s return. The day came. Many Bahá’ís had gone to meet Him, though Lua and Grace had remained at the house to welcome Him. The door opened, He came in. He welcomed Lua warmly, glanced at Grace as at a complete stranger, and turned away. Grace was appalled, shocked. Hadn't He recognized her? Had He forgotten her? Had she misunderstood the permission to come to New York? Or had she displeased Him and was this punishment? Whatever it was, it continued with no let-up. During all the days that followed ‘Abdu’l-Bahá never showed by word or glance that He recognized her in any way - except to put her to work. Whenever she relaxed at all throughout any day, word would come at once, through Lua, setting her to work harder at some new task. She worked in that household until long after midnight - cleaning, cooking, scrubbing, and then she would rise at five in the morning to begin all over again. She worked as she had never worked before in all her life and ‘Abdu’l-Bahá ignored her completely. If they ever chanced to meet he would draw aside His robe for her to pass and his glance would go through her as if she were not there. At last came the day when the movies of ‘Abdu’l-Bahá were to be taken over in Brooklyn at the home of Howard MacNutt. And Grace thought, wearily, \"at least I will be included in THIS since EVERYONE in the household is to go.\" But, an hour before the several carloads of people were scheduled to leave, Lua came to Grace to say that ‘Abdu’l-Bahá felt that someone should remain at the house to welcome two ladies who were expected that morning, and Grace was to be the one to stay behind. So when the cars left - Grace stood at the top of the flight of brownstone steps and watched them all roll away. Then, she turned and went into the empty house. For a moment she stood there, fighting the feeling of desolation and abandonment and loneliness, and then she thought of the white roses that had been delivered that morning, as they were daily, for ‘Abdu’l-Bahá’s room. The one bright spot in these dreadful days for Grace had been that she was the one to arrange these roses each morning. So, with the long florists' box in her arms, she climbed up to ‘Abdu’l-Bahá’s room at the top of the house, where He had wished to be. She reached the top of the third flight - and found the door not only closed, but locked against her. And always before it had stood wide open! This, for Grace, was the last straw. Overwhelmed by all the hurt and bewilderment of all these days, she sank down on the floor and wept",
      "with the fallen roses scattered around her. At last, the sobs faded, her tears spent themselves, and, exhausted, she gathered up the roses and went back downstairs. The expected ladies had not arrived, nor did they ever arrive. But Grace - it was now past noon - was hungry. So, she went down to the kitchen to get something to eat. And in that house that fed, each day, so many dozens of people, there was nothing to eat but one egg and a small piece of leftover bread in ‘Abdu’l-Bahá’s bread-box. (this bread was especially baked for Him by a Persian believer who had begged to come on this journey just so he might cook ‘Abdu’l-Bahá’s food). So Grace boiled her one egg and put her small portion of bread on a plate. Putting the egg in an egg cup, she chipped the shell - and the egg, as bad as an egg can get, exploded in her face. She cleaned up the mess and returned to her bit of leftover bread. And, as she crumbled the bread, eating it crumb by crumb she realized, suddenly, exactly what she was doing - she was, blessedly, eating the crumbs of the bread of life from ‘Abdu’l-Bahá’s table. She began to eat even more slowly as the spirit of prayer came to possess her. Not long after this the household returned from Brooklyn - and that evening Lua came to Grace and said, \"The Master has asked me to tell you that He knows you wept.\" And this was the first time it had occurred to Grace that all this dreadful experience might have a reason, a pattern. And - if this were true she must find out what the reason could be. So she went up to her room to pray about it. To pray for illumination and wisdom and the selflessness to understand. And as she prayed she heard a small voice saying 'Are you as happy scrubbing the garbage pails as you are arranging the roses?' And she suddenly realized what the spirit of true service was. It was to rise to selfless joy in offering the service, no matter what form that service might take. And as this truth swept over her, suffusing her, illuminating her, the door opened, and ‘Abdu’l-Bahá walked into the room. His arms were outstretched; His dear face was glorified. \"Welcome!\" He cried to Grace, \"Welcome to the Kingdom!\" And he held her close, embracing her deeply. And never did He withdraw Himself from her again."
    ]
  },
  {
    id: "street-of-akka-friday-giving",
    theme: "generosity",
    author: "Myron Henry Phelps and Bahiyyih Khánum",
    book: "Life and Teachings of Abbas Effendi",
    chapter: "Poor",
    sourceDetail:
      "From Bahá'í Stories; Myron Henry Phelps and Bahiyyih Khánum, Life and Teachings of Abbas Effendi.",
    title: "In each open palm he places some small coins.",
    quote: "Marhabbah, marhabbah",
    readTime: "4 minute read",
    tags: ["Generosity", "Compassion", "‘Akká", "Poor", "Children"],
    summary:
      "A visitor looks down into a narrow street of ‘Akká and watches ‘Abdu’l-Bahá greet the poor one by one.",
    source: "https://bahaistories.com/subject/poor",
    image: "",
    imageAlt: "",
    addedOn: "2026-04-30",
    story: [
      "Imagine that we are in the ancient house of the still more ancient city of Akka, which was for a month my home. The room in which we are faces the opposite wall of a narrow paved street, which an active man might clear at a single bound. Above is the bright sun of Palestine; to the right a glimpse of the old sea-wall and the blue Mediterranean. As we sit we hear a singular sound rising from the pavement, thirty feet below - faint at first, and increasing. It is like the murmur of human voices.",
      "We open the window and look down. We see a crowd of human beings with patched and tattered garments. Let us descend to the street and see who these are.",
      "It is a noteworthy gathering. Many of these men are blind; many more are pale, emaciated, or aged. Some are on crutches; some are so feeble that they can barely walk. Most of the women are closely veiled, but enough are uncovered to cause us well to believe that, if the veils were lifted, more pain and misery would be seen. Some of them carry babes with pinched and sallow faces. There are perhaps a hundred in this gathering, and besides, many children.",
      "They are of all the races one meets in these streets - Syrians, Arabs, Ethiopians, and many others. These people are ranged against the walls or seated on the ground, apparently in an attitude of expectation; - for what do they wait? Let us wait with them.",
      "We have not to wait long. A door opens and a man comes out. He is of middle stature, strongly built. He wears flowing light-coloured robes. On his head is a light buff fez with a white cloth wound about it. He is perhaps sixty years of age. His long grey hair rests on his shoulders. His forehead is broad, full, and high, his nose slightly aquiline, his moustaches and beard, the latter full though not heavy, nearly white. His eyes are grey and blue, large, and both soft and penetrating.",
      "His bearing is simple, but there is grace, dignity, and even majesty about his movements. He passes through the crowd, and as he goes utters words of salutation. We do not understand them, but we see the benignity and the kindliness of his countenance. He stations himself at a narrow angle of the street and motions to the people to come towards him. They crowd up a little too insistently. He pushes them gently back and lets them pass him one by one. As they come they hold their hands extended.",
      "In each open palm he places some small coins. He knows them all. He caresses them with his hand on the face, on the shoulders, on the head. Some he stops and questions. An aged negro who hobbles up, he greets with some kindly inquiry; the old man's broad face breaks into a sunny smile, his white teeth glistening against his ebony skin as he replies. He stops a woman with a babe and fondly strokes the child. As they pass, some kiss his hand. To all he says, \"Marhabbah, marhabbah\" - \"Well done, well done!\"",
      "So they all pass him. The children have been crowding around him with extended hands, but to them he has not given. However, at the end, as he turns to go, he throws a handful of coppers over his shoulder, for which they scramble.",
      "During this time this friend of the poor has not been unattended. Several men wearing red fezes, and with earnest and kindly faces, followed him from the house, stood near him and aided in regulating the crowd, and now, with reverent manner and at a respectful distance, follow him away. When they address him they call him \"Master.\""
    ]
  },
  {
    id: "ustad-baqir-ustad-ahmad",
    theme: "steadfastness",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Ustád Báqir and Ustád Aḥmad",
    sourcePages: "section 27",
    sourceDetail:
      "From the Bahá'í Reference Library; ‘Abdu'l-Bahá, Memorials of the Faithful.",
    title: "Ustád Báqir and Ustád Aḥmad.",
    quote: "They were two most blessed souls.",
    readTime: "2 minute read",
    tags: ["Steadfastness", "Brotherhood", "Exile", "Craft", "Faith"],
    summary:
      "A complete memorial for two brothers whose carpentry, exile, prayer, and patience were remembered together.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/3",
    image: "",
    imageAlt: "",
    addedOn: "2026-04-30",
    story: [
      "And again among those who left their homeland were two carpenters, Ustád Báqir and Ustád Aḥmad. These two were brothers, of pure lineage, and natives of Ká sh án. From the time when both became believers each held the other in his embrace. They harkened to the voice of God, and to His cry of “Am I not your Lord?” they replied, “Yea, verily!”",
      "For a time they stayed on in their own country, occupied with the remembrance of God, characterized by faith and knowledge, respected by friend and stranger alike, known to all for righteousness and trustworthiness, for austerity of life and the fear of God. When the oppressor stretched forth his hands against them, and tormented them beyond endurance, they emigrated to Iraq, to the sheltering care of Bahá’u’lláh. They were two most blessed souls.",
      "For some time they remained in Iraq, praying in all lowliness, and supplicating God.",
      "Then Ustád Aḥmad departed for Adrianople, while Ustád Báqir remained in Iraq and was taken as a prisoner to Mosul. Ustád Aḥmad went on with the party of Bahá’u’lláh to the Most Great Prison, and Ustád Báqir emigrated from Mosul to ‘Akká. Both of the brothers were under the protection of God and free from every earthly bond. In the prison, they worked at their craft, keeping to themselves, away from friend and stranger alike.",
      "Tranquil, dignified, confident, strong in faith, sheltered by the All-Merciful, they happily spent their days. Ustád Báqir was the first to die, and some time afterward his brother followed him.",
      "These two were firm believers, loyal, patient, at all times thankful, at all times supplicating God in lowliness, with their faces turned in His direction. During that long stay in the prison they were never neglectful of duty, never at fault. They were constantly joyful, for they had drunk deep of the holy cup; and when they soared upward, out of the world, the friends mourned over them and asked that by the grace of Bahá’u’lláh, they should be favored and forgiven.",
      "These two were embosomed in bounty, and Divinely sustained, and the Blessed Beauty was well pleased with them both; with this provision for their journey, they set out for the world to come. Upon them both be the glory of God the All-Glorious; to each be a seat of truth in the Kingdom of Splendors."
    ]
  },
  {
    id: "rizwanea-sacrifice",
    theme: "sacrifice",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Sacrifice",
    sourcePages: "pp. 14-15",
    sourceDetail:
      "From Bahá'í Stories; Reginald Grant Barrow, Mother's Stories, pp. 14-15.",
    title: "Rizwanea asks for one more day.",
    quote: "Teach me to be grateful!",
    readTime: "5 minute read",
    tags: ["Sacrifice", "Detachment", "Gratitude", "Marriage", "Service"],
    summary:
      "After years of travel, teaching, and rootlessness, Rizwanea reaches the end of her strength and spends one decisive day in prayer.",
    source: "https://bahaistories.com/subject/sacrifice",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Wilmette_how_side.jpg",
    featureImageAlt: "Bahá'í House of Worship in Wilmette seen from the side",
    story: [
      "Mable Ives, after she married Howard Colby Ives, became known to many who loved her as Rizwanea. For very many years, after they were married, my father and Rizwanea traveled and taught the Faith. It was their entire life.",
      "They traveled through the New England states, through Pennsylvania, Ohio, Illinois, New York and many many more - always teaching, always leaving an established Assembly behind them. It was a gypsy life.",
      "It meant that never once, during all the years, did they really have a home; no place where they might be surrounded by their own things, where they might put down roots. Always they lived surrounded by strange and alien furniture, by the bare wall and arid atmosphere of barren hotels, boarding houses, and cubbyholes where they might sleep while, during their waking hours, they earned their living and taught their beloved Faith.",
      "At last, after many years, with her health failing, Rizwanea felt she could endure no more. She had come to the end. She must have a home. She needed it with every atom of her being - needed it as a bird needs to make a nest in the springtime or as anyone, weary and spent, needs to rest in the sun.",
      "At this time they - she and my father were living in a particularly difficult situation. It was a furnished room and the landlady was constantly complaining of everything they did. They used too many lights, they took too many showers using up too much water, and the clacking of Father's typewriter was driving her crazy.",
      "So, one morning, Rizwanea told Father how she felt: She had come to the end; she could endure no more; she was unable to go one step farther. They had a long period of consultation, and at the end, Father told her that, of course, he would do as she wished, but would she, in turn, do one thing for him? Would she wait just one more day before making a truly final decision - and would she spend this day in prayer?",
      "She agreed. So after Father had left her to go out and attend to his business details, she kept her promise. She began to pray. And as she prayed, it came to her just what, in its depth and beauty, submission, detachment, and servitude really meant. And it came to her that submission - true and complete submission to the Will of God - was the first basic step.",
      "So she began to pray for submission - she prayed and prayed, and finally, submission came to her - but with it came the realization that submission was not enough. Well, then, what was enough? What should she pray for now?",
      "And she remembered that Bahá'u'lláh had written that we must be grateful for the circumstances to which we were submitting. Grateful? Grateful for this horrid little room? Grateful for the beastly, complaining landlady? Well, all right - if Bahá'u'lláh said so she, Rizwanea, would be grateful. But it wasn't easy. She was pacing the room, thinking, praying, fighting and now she went to the window to stare out into the street.",
      "'Teach me to be grateful! Teach me to be submissive! I will be grateful! I will be submissive!' She clenched her small fists. She fought and she suffered. And, finally, the first warm touch and then the warmer flow of submissive gratitude surged over her.",
      "But, the next moment, she realized that even this was not enough. Not enough? When she'd fought so hard and she was so tired. What then was left? What should she pray for next?",
      "And it came to her that now she must pray for love. Love for her nerve-wracking circumstances; love for her harsh landlady; love for the whole situation that had led to the crisis - the blessed crisis that had forced her to learn this lesson.",
      "So, now, Rizwanea prayed that she might love, that she might be filled with love, that she might be able to pour out this love. And her prayers were answered.",
      "When Father returned to her, it was to meet a radiant woman - a woman filled with the glory of complete submission to the Will of God - a woman rich with the glory of gratitude for tests - a woman overflowing with the clear crystal waters of the love of God.",
      "And, for many years more, she poured out these waters for the glory of the Cause she loved so well."
    ]
  },
  {
    id: "tahirih",
    theme: "courage",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Ṭáhirih",
    sourcePages: "section 69",
    sourceDetail:
      "From the Bahá'í Reference Library; ‘Abdu'l-Bahá, Memorials of the Faithful.",
    title: "Ṭáhirih, the Pure One.",
    quote: "Let deeds, not words, be our adorning!",
    readTime: "20 minute read",
    narration: {
      provider: "openai",
      assetKey: "tahirih",
      model: "gpt-4o-mini-tts",
      voice: "coral",
      status: "pending"
    },
    tags: ["Courage", "Learning", "Women", "Martyrdom", "Badasht"],
    summary:
      "The story of Ṭáhirih: her learning, recognition of the Báb, public teaching, Badasht, captivity, and martyrdom.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/6#992784946",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bah%C3%A1%27%C3%AD_gardens.jpg",
    featureImageAlt: "Bahá'í gardens on Mount Carmel in Haifa",
    story: [
      "A woman chaste and holy, a sign and token of surpassing beauty, a burning brand of the love of God, a lamp of His bestowal, was Jináb-i-Ṭáhirih. She was called Umm-Salmá; she was the daughter of Ḥájí Mullá Ṣáliḥ, a mujtahid of Qazvín, and her paternal uncle was Mullá Taqí, the Imám-Jum‘ih or leader of prayers in the cathedral mosque of that city. They married her to Mullá Muḥammad, the son of Mullá Taqí, and she gave birth to three children, two sons and a daughter; all three were bereft of the grace that encompassed their mother, and all failed to recognize the truth of the Cause.",
      "When she was still a child her father selected a teacher for her and she studied various branches of knowledge and the arts, achieving remarkable ability in literary pursuits. Such was the degree of her scholarship and attainments that her father would often express his regret, saying, “Would that she had been a boy, for he would have shed illumination upon my household, and would have succeeded me!”",
      "One day she was a guest in the home of Mullá Javád, a cousin on her mother’s side, and there in her cousin’s library she came upon some of the writings of Shaykh Aḥmad-i-Aḥsá’í. Delighted with what he had to say, Ṭáhirih asked to borrow the writings and take them home. Mullá Javád violently objected, telling her: “Your father is an enemy of the Twin Luminous Lights, Shaykh Aḥmad and Siyyid Káẓim. If he should even dream that any words of those two great beings, any fragrance from the garden of those realities, had come your way, he would make an attempt against my life, and you too would become the target of his wrath.” Ṭáhirih answered: “For a long time now, I have thirsted after this; I have yearned for these explanations, these inner truths. Give me whatever you have of these books. Never mind if it angers my father.” Accordingly, Mullá Javád sent over the writings of the Shaykh and the Siyyid.",
      "One night, Ṭáhirih sought out her father in his library, and began to speak of Shaykh Aḥmad’s teachings. The very moment he learned that his daughter knew of the Shaykhí doctrines, Mullá Ṣáliḥ’s denunciations rang out, and he cried: “Javád has made you a lost soul!” Ṭáhirih answered, “The late Shaykh was a true scholar of God, and I have learned an infinity of spiritual truths from reading his books. Furthermore, he bases whatever he says on the traditions of the Holy Imáms. You call yourself a mystic knower and a man of God, you consider your respected uncle to be a scholar as well, and most pious—yet in neither of you do I find a trace of those qualities!”",
      "For some time, she carried on heated discussions with her father, debating such questions as the Resurrection and the Day of Judgment, the Night-Ascent of Muḥammad to Heaven, the Promise and the Threat, and the Advent of the Promised One. Lacking arguments, her father would resort to curses and abuse. Then one night, in support of her contention, Ṭáhirih quoted a holy tradition from the Imám Ja‘far-i-Ṣádiq; and since it confirmed what she was saying, her father burst out laughing, mocking the tradition. Ṭáhirih said, “Oh my father, these are the words of the Holy Imám. How can you mock and deny them?”",
      "From that time on, she ceased to debate and contend with her father. Meanwhile she entered into secret correspondence with Siyyid Káẓim, regarding the solution of complex theological problems, and thus it came about that the Siyyid conferred on her the name “Solace of the Eyes” (Qurratu’l-‘Ayn); as for the title Ṭáhirih (“The Pure One”), it was first associated with her in Badasht, and was subsequently approved by the Báb, and recorded in Tablets.",
      "Ṭáhirih had caught fire. She set out for Karbilá, hoping to meet Siyyid Káẓim, but she arrived too late: ten days before she reached that city, he passed away. Not long before his death the Siyyid had shared with his disciples the good news that the promised Advent was at hand. “Go forth,” he repeatedly told them, “and seek out your Lord.” Thus the most distinguished of his followers gathered for retirement and prayer, for fasts and vigils, in the Masjid-i-Kúfih, while some awaited the Advent in Karbilá. Among these was Ṭáhirih, fasting by day, practicing religious disciplines, and spending the night in vigils, and chanting prayers. One night when it was getting along toward dawn she laid her head on her pillow, lost all awareness of this earthly life, and dreamed a dream; in her vision a youth, a Siyyid, wearing a black cloak and a green turban, appeared to her in the heavens; he was standing in the air, reciting verses and praying with his hands upraised. At once, she memorized one of those verses, and wrote it down in her notebook when she awoke. After the Báb had declared His mission, and His first book, “The Best of Stories,” was circulated, Ṭáhirih was reading a section of the text one day, and she came upon that same verse, which she had noted down from the dream. Instantly offering thanks, she fell to her knees and bowed her forehead to the ground, convinced that the Báb’s message was truth.",
      "This good news reached her in Karbilá and she at once began to teach. She translated and expounded “The Best of Stories,” also writing in Persian and Arabic, composing odes and lyrics, and humbly practicing her devotions, performing even those that were optional and supernumerary. When the evil ‘ulamás in Karbilá got wind of all this, and learned that a woman was summoning the people to a new religion and had already influenced a considerable number, they went to the Governor and lodged a complaint. Their charges, to be brief, led to violent attacks on Ṭáhirih, and sufferings, which she accepted and for which she offered praise and thanks. When the authorities came hunting for her they first assaulted Shamsu’ḍ-Ḍuḥá, mistaking her for Ṭáhirih. As soon, however, as they heard that Ṭáhirih had been arrested they let Shams go—for Ṭáhirih had sent a message to the Governor saying, “I am at your disposal. Do not harm any other.”",
      "The Governor set guards over her house and shut her away, writing Baghdad for instructions as to how he should proceed. For three months, she lived in a state of siege, completely isolated, with the guards surrounding her house. Since the local authorities had still received no reply from Baghdad, Ṭáhirih referred her case to the Governor, saying: “No word has come from either Baghdad or Constantinople. Accordingly, we will ourselves proceed to Baghdad and await the answer there.” The Governor gave her leave to go, and she set out, accompanied by Shamsu’ḍ-Ḍuḥá and the Leaf of Paradise (the sister of Mullá Ḥusayn) and her mother. In Baghdad she stayed first in the house of Shaykh Muḥammad, the distinguished father of Áqá Muḥammad-Muṣṭafá. But so great was the press of people around her that she transferred her residence to another quarter, engaged night and day in spreading the Faith, and freely associated with the inhabitants of Baghdad. She thus became celebrated throughout the city and there was a great uproar.",
      "Ṭáhirih also maintained a correspondence with the ‘ulamás of Káẓimayn; she presented them with unanswerable proofs, and when one or another appeared before her she offered him convincing arguments. Finally she sent a message to the Shí‘ih divines, saying to them: “If you are not satisfied with these conclusive proofs, I challenge you to a trial by ordeal.” Then there was a great outcry from the divines, and the Governor was obliged to send Ṭáhirih and her women companions to the house of Ibn-i-Álúsí, who was muftí of Baghdad. Here she remained about three months, waiting for word and directions from Constantinople. Ibn-i-Álúsí would engage her in learned dialogues, questions would be asked and answers given, and he would not deny what she had to say.",
      "On a certain day the muftí related one of his dreams, and asked her to tell him what it meant. He said: “In my dream I saw the Shí‘ih ‘ulamás arriving at the holy tomb of Imám Ḥusayn, the Prince of Martyrs. They took away the barrier that encloses the tomb, and they broke open the resplendent grave, so that the immaculate body lay revealed to their gaze. They sought to take up the holy form, but I cast myself down on the corpse and I warded them off.” Ṭáhirih answered: “This is the meaning of your dream: you are about to deliver me from the hands of the Shí‘ih divines.” “I too had interpreted it thus,” said Ibn-i-Álúsí.",
      "Since he had discovered that she was well versed in learned questions and in sacred commentaries and Texts, the two often carried on debates; she would speak on such themes as the Day of Resurrection, the Balance, and the Ṣiráṭ, and he would not turn away.",
      "Then came a night when the father of Ibn-i-Álúsí called at the house of his son. He had a meeting with Ṭáhirih and abruptly, without asking a single question, began to curse, mock and revile her. Embarrassed at his father’s behavior, Ibn-i-Álúsí apologized. Then he said: “The answer has come from Constantinople. The King has commanded that you be set free, but only on condition that you leave his realms. Go then, tomorrow, make your preparations for the journey, and hasten away from this land.”",
      "Accordingly Ṭáhirih, with her women companions, left the muftí’s house, saw to arranging for their travel gear, and went out of Baghdad. When they left the city, a number of Arab believers, carrying arms, walked along beside their convoy. Among the escort were Shaykh Sulṭán, Shaykh Muḥammad and his distinguished son Muḥammad-Muṣṭafá, and Shaykh Ṣáliḥ, and these were mounted. It was Shaykh Muḥammad who defrayed the expenses of the journey.",
      "When they reached Kirmánsháh the women alighted at one house, the men at another, and the inhabitants arrived in a continuous stream to seek information as to the new Faith. Here as elsewhere the ‘ulamás were soon in a state of frenzy and they commanded that the newcomers be expelled. As a result the kad-khudá or chief officer of that quarter, with a band of people, laid siege to the house where Ṭáhirih was, and sacked it. Then they placed Ṭáhirih and her companions in an uncovered howdah and carried them from the town to an open field, where they put the captives out. The drivers then took their animals and returned to the city. The victims were left on the bare ground, with no food, no shelter, and no means of traveling on.",
      "Ṭáhirih at once wrote a letter to the prince of that territory, in which she told him: “O thou just Governor! We were guests in your city. Is this the way you treat your guests?” When her letter was brought to the Governor of Kirmánsháh he said: “I knew nothing of this injustice. This mischief was kindled by the divines.” He immediately commanded the kad-khudá to return all the travelers’ belongings. That official duly surrendered the stolen goods, the drivers with their animals came back out of the city, the travelers took their places and resumed the journey.",
      "They arrived in Hamadán and here their stay was a happy one. The most illustrious ladies of that city, even the princesses, would come to visit, seeking the benefits of Ṭáhirih’s teaching. In Hamadán she dismissed a part of her escort and sent them back to Baghdad, while she brought some of them, including Shamsu’ḍ-Ḍuḥá and Shaykh-Ṣáliḥ, along with her to Qazvín.",
      "As they traveled, some riders advanced to meet them, kinsmen of Ṭáhirih’s from Qazvín, and they wished to lead her away alone, unescorted by the others, to her father’s house. Ṭáhirih refused, saying: “These are in my company.” In this way they entered Qazvín. Ṭáhirih proceeded to her father’s house, while the Arabs who had formed her escort alighted at a caravanserai. Ṭáhirih soon left her father and went to live with her brother, and there the great ladies of the city would come to visit her; all this until the murder of Mullá Taqí, when every Bábí in Qazvín was taken prisoner. Some were sent to Ṭihrán and then returned to Qazvín and martyred.",
      "Mullá Taqí’s murder came about in this way: One day, when that besotted tyrant had mounted his pulpit, he began to mock and revile the great Shaykh Aḥmad-i-Aḥsá’í. Shamelessly, grossly, screaming obscenities, he cried out: “That Shaykh is the one who has kindled this fire of evil, and subjected the whole world to this ordeal!” There was an inquirer in the audience, a native of Shíráz. He found the taunts, jeers and indecencies to be more than he could bear. Under cover of darkness he betook himself to the mosque, plunged a spearhead between the lips of Mullá Taqí and fled. The next morning they arrested the defenseless believers and thereupon subjected them to agonizing torture, though all were innocent and knew nothing of what had come to pass. There was never any question of investigating the case; the believers repeatedly declared their innocence but no one paid them any heed. When a few days had passed the killer gave himself up; he confessed to the authorities, informing them that he had committed the murder because Mullá Taqí had vilified Shaykh Aḥmad. “I deliver myself into your hands,” he told them, “so that you will set these innocent people free.” They arrested him as well, put him in the stocks, chained him, and sent him in chains, along with the others, to Ṭihrán.",
      "Once there he observed that despite his confession, the others were not released. By night, he made his escape from the prison and went to the house of Riḍá Khán—that rare and precious man, that star-sacrifice among the lovers of God—the son of Muḥammad Khán, Master of the Horse to Muḥammad Sháh. He stayed there for a time, after which he and Riḍá Khán secretly rode away to the Fort of Shaykh Ṭabarsí in Mázindarán. Muḥammad Khán sent riders after them to track them down, but try as they might, no one could find them. Those two horsemen got to the Fort of Ṭabarsí, where both of them won a martyr’s death. As for the other friends who were in the prison at Ṭihrán, some of these were returned to Qazvín and they too suffered martyrdom.",
      "One day the administrator of finance, Mírzá Shafí‘, called in the murderer and addressed him, saying: “Jináb, do you belong to a dervish order, or do you follow the Law? If you are a follower of the Law, why did you deal that learned mujtahid a cruel, a fatal blow in the mouth? If you are a dervish and follow the Path, one of the rules of the Path is to harm no man. How, then, could you slaughter that zealous divine?” “Sir,” he replied, “besides the Law, and besides the Path, we also have the Truth. It was in serving the Truth that I paid him for his deed.”",
      "These things would take place before the reality of this Cause was revealed and all was made plain. For in those days no one knew that the Manifestation of the Báb would culminate in the Manifestation of the Blessed Beauty and that the law of retaliation would be done away with, and the foundation-principle of the Law of God would be this, that “It is better for you to be killed than to kill”; that discord and contention would cease, and the rule of war and butchery would fall away. In those days, that sort of thing would happen. But praised be God, with the advent of the Blessed Beauty such a splendor of harmony and peace shone forth, such a spirit of meekness and long-suffering, that when in Yazd men, women and children were made the targets of enemy fire or were put to the sword, when the leaders and the evil ‘ulamás and their followers joined together and unitedly assaulted those defenseless victims and spilled out their blood—hacking at and rending apart the bodies of chaste women, with their daggers slashing the throats of children they had orphaned, then setting the torn and mangled limbs on fire—not one of the friends of God lifted a hand against them. Indeed, among those martyrs, those real companions of the ones who died, long gone, at Karbilá, was a man who, when he saw the drawn sword flashing over him, thrust sugar candy into his murderer’s mouth and cried, “With a sweet taste on your lips, put me to death—for you bring me martyrdom, my dearest wish!”",
      "Let us return to our theme. After the murder of her impious uncle, Mullá Taqí, in Qazvín, Ṭáhirih fell into dire straits. She was a prisoner and heavy of heart, grieving over the painful events that had come to pass. She was watched on every side, by attendants, guards, the farráshes, and her foes. While she languished thus, Bahá’u’lláh dispatched Hádíy-i-Qazvíní, husband of the celebrated Khátún-Ján, from the capital, and they managed, by a stratagem, to free her from that embroilment and got her to Ṭihrán in the night. She alighted at the mansion of Bahá’u’lláh and was lodged in an upper apartment.",
      "When word of this spread throughout Ṭihrán, the Government hunted for her high and low; nevertheless, the friends kept arriving to see her, in a steady stream, and Ṭáhirih, seated behind a curtain, would converse with them. One day the great Siyyid Yaḥyá, surnamed Vaḥíd, was present there. As he sat without, Ṭáhirih listened to him from behind the veil. I was then a child, and was sitting on her lap. With eloquence and fervor, Vaḥíd was discoursing on the signs and verses that bore witness to the advent of the new Manifestation. She suddenly interrupted him and, raising her voice, vehemently declared: “O Yaḥyá! Let deeds, not words, testify to thy faith, if thou art a man of true learning. Cease idly repeating the traditions of the past, for the day of service, of steadfast action, is come. Now is the time to show forth the true signs of God, to rend asunder the veils of idle fancy, to promote the Word of God, and to sacrifice ourselves in His path. Let deeds, not words, be our adorning!”",
      "The Blessed Beauty made elaborate arrangements for Ṭáhirih’s journey to Badasht and sent her off with an equipage and retinue. His own party left for that region some days afterward.",
      "In Badasht, there was a great open field. Through its center a stream flowed, and to its right, left, and rear there were three gardens, the envy of Paradise. One of those gardens was assigned to Quddús, but this was kept a secret. Another was set apart for Ṭáhirih, and in a third was raised the pavilion of Bahá’u’lláh. On the field amidst the three gardens, the believers pitched their tents. Evenings, Bahá’u’lláh, Quddús and Ṭáhirih would come together. In those days the fact that the Báb was the Qá’im had not yet been proclaimed; it was the Blessed Beauty, with Quddús, Who arranged for the proclamation of a universal Advent and the abrogation and repudiation of the ancient laws.",
      "Then one day, and there was a wisdom in it, Bahá’u’lláh fell ill; that is, the indisposition was to serve a vital purpose. On a sudden, in the sight of all, Quddús came out of his garden, and entered the pavilion of Bahá’u’lláh. But Ṭáhirih sent him a message, to say that their Host being ill, Quddús should visit her garden instead. His answer was: “This garden is preferable. Come, then, to this one.” Ṭáhirih, with her face unveiled, stepped from her garden, advancing to the pavilion of Bahá’u’lláh; and as she came, she shouted aloud these words: “The Trumpet is sounding! The great Trump is blown! The universal Advent is now proclaimed!” The believers gathered in that tent were panic struck, and each one asked himself, “How can the Law be abrogated? How is it that this woman stands here without her veil?”",
      "“Read the Súrih of the Inevitable,” said Bahá’u’lláh; and the reader began: “When the Day that must come shall have come suddenly… Day that shall abase! Day that shall exalt!…” and thus was the new Dispensation announced and the great Resurrection made manifest. At the start, those who were present fled away, and some forsook their Faith, while some fell a prey to suspicion and doubt, and a number, after wavering, returned to the presence of Bahá’u’lláh. The Conference of Badasht broke up, but the universal Advent had been proclaimed.",
      "Afterward, Quddús hastened away to the Fort of Ṭabarsí and the Blessed Beauty, with provisions and equipment, journeyed to Níyálá, having the intention of going on from there by night, making His way through the enemy encampment and entering the Fort. But Mírzá Taqí, the Governor of Ámul, got word of this, and with seven hundred riflemen arrived in Níyálá. Surrounding the village by night, he sent Bahá’u’lláh with eleven riders back to Ámul, and those calamities and tribulations, told of before, came to pass.",
      "As for Ṭáhirih, after the breakup at Badasht she was captured, and the oppressors sent her back under guard to Ṭihrán. There she was imprisoned in the house of Maḥmúd Khán, the Kalántar. But she was aflame, enamored, restless, and could not be still. The ladies of Ṭihrán, on one pretext or another, crowded to see and listen to her. It happened that there was a celebration at the Mayor’s house for the marriage of his son; a nuptial banquet was prepared, and the house adorned. The flower of Ṭihrán’s ladies were invited, the princesses, the wives of vazírs and other great. A splendid wedding it was, with instrumental music and vocal melodies—by day and night the lute, the bells and songs. Then Ṭáhirih began to speak; and so bewitched were the great ladies that they forsook the cithern and the drum and all the pleasures of the wedding feast, to crowd about Ṭáhirih and listen to the sweet words of her mouth.",
      "Thus she remained, a helpless captive. Then came the attempt on the life of the Sháh; a farmán was issued; she was sentenced to death. Saying she was summoned to the Prime Minister’s, they arrived to lead her away from the Kalántar’s house. She bathed her face and hands, arrayed herself in a costly dress, and scented with attar of roses she came out of the house.",
      "They brought her into a garden, where the headsmen waited; but these wavered and then refused to end her life. A slave was found, far gone in drunkenness; besotted, vicious, black of heart. And he strangled Ṭáhirih. He forced a scarf between her lips and rammed it down her throat. Then they lifted up her unsullied body and flung it in a well, there in the garden, and over it threw down earth and stones. But Ṭáhirih rejoiced; she had heard with a light heart the tidings of her martyrdom; she set her eyes on the supernal Kingdom and offered up her life.",
      "Salutations be unto her, and praise. Holy be her dust, as the tiers of light come down on it from Heaven."
    ]
  },
  {
    id: "harry-randall-guidance",
    theme: "intuition",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Intuition",
    sourcePages: "p. 24",
    sourceDetail:
      "From Bahá'í Stories; Reginald Grant Barrow, Mother's Stories, p. 24.",
    title: "Harry Randall follows intuition.",
    quote: "John, John he's come!",
    readTime: "3 minute read",
    tags: ["Intuition", "Teaching", "Dreams", "Trust", "Search"],
    collectionTags: ["Anecdotes"],
    summary:
      "Harry Randall prays at each crossing until a long walk brings him to the door of someone already waiting.",
    source: "https://bahaistories.com/subject/intuition",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bahai_Gardens_Haifa.jpg",
    featureImageAlt: "Terraces and gardens near the Shrine of the Báb in Haifa",
    story: [
      "Harry Randall, once he had leaped the hurdle and become a Bahá’í was a very enthusiastic one. When Harlan told him about 'guidance' - what a mystery it was, and how earnestly Harlan himself was trying to understand and live under it Harry, too, began to try to apply it. One afternoon he started out to take a walk and, in an effort to understand this guidance that Harlan talked about, Harry paused at each cross street and corner praying that he might be urged in whatever direction it might be that God wished him to take. He walked and walked, the city streets gave way to country roads and still he walked. At some corners he was moved to turn; at some he went straight ahead. But he felt no urge to stop he felt strongly that he should keep going. Finally, at the end of the afternoon, he came to a small white house surrounded by a picket fence - and here, with his hand on the gate, he knew this was the house he had been led to; this was the end of his walk. So he opened the gate, went up the short path and knocked at the door. A woman opened the door and, giving him one look, called back over her shoulder, 'John, John he's come!'  It seems that the night before, this woman had had a dream in which she had gone to open her door to one who knocked - a man who had come into her house and told her something that was so exciting and wonderful that when she woke up - though she couldn't remember what the exciting and wonderful thing had been - she was still so excited she'd told her husband about it. And then Harry had knocked - Harry had come into her house and Harry had told her about Bahá’u’lláh and given her the wonderful Message for the New Day."
    ]
  },
  {
    id: "mishkin-qalam",
    theme: "service",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "Mishkín-Qalam",
    sourcePages: "section 38",
    sourceDetail:
      "From the Bahá'í Reference Library; ‘Abdu'l-Bahá, Memorials of the Faithful.",
    title: "Mishkín-Qalam.",
    quote: "nor ever fail in service",
    readTime: "6 minute read",
    tags: ["Service", "Art", "Teaching", "Steadfastness", "Exile"],
    summary:
      "The complete memorial of Mishkín-Qalam, calligrapher, exile, and faithful companion.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/4#604886557",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Shrine_of_Bah%C3%A1%27u%27ll%C3%A1h.jpg",
    featureImageAlt: "The Shrine of Bahá'u'lláh near Bahjí",
    story: [
      "Among the exiles, neighbors, and prisoners there was also a second Mír ‘Imád, the eminent calligrapher, Mishkín-Qalam. He wielded a musk-black pen, and his brows shone with faith. He was among the most noted of mystics, and had a witty and subtle mind. The fame of this spiritual wayfarer reached out to every land. He was the leading calligrapher of Persia and well known to all the great; he enjoyed a special position among the court ministers of Ṭihrán, and with them he was solidly established. He was famed throughout Asia Minor; his pen was the wonder of all calligraphers, for he was adept at every calligraphic style. He was besides, for human virtues, a bright star.",
      "This highly accomplished man first heard of the Cause of God in Iṣfahán, and the result was that he set out to find Bahá’u’lláh. He crossed the great distances, measured out the miles, climbing mountains, passing over deserts and over the sea, until at last he came to Adrianople. Here he reached the heights of faith and assurance; here he drank the wine of certitude. He responded to the summons of God, he attained the presence of Bahá’u’lláh, he ascended to that apogee where he was received and accepted. By now he was reeling to and fro like a drunkard in his love for God, and because of his violent desire and yearning, his mind seemed to wander. He would be raised up, and then cast down again; he was as one distracted. He spent some time under the sheltering grace of Bahá’u’lláh, and every day new blessings were showered upon him. Meanwhile he produced his splendid calligraphs; he would write out the Most Great Name, Yá Bahá’u’l-Abhá, O Thou Glory of the All-Glorious, with marvelous skill, in many different forms, and would send them everywhere.",
      "He was then directed to go on a journey to Constantinople, and set out with Jináb-i-Sayyáḥ. When he reached that Great City, the leading Persians and Turks received him with every honor at first, and they were captivated by his jet black, calligraphic art. He, however, began boldly and eloquently to teach the Faith. The Persian ambassador lurked in ambush; betaking himself to the Sulṭán’s vazírs he slandered Mishkín-Qalam. “This man is an agitator,” the ambassador told them, “sent here by Bahá’u’lláh to stir up trouble and make mischief in this Great City. He has already won over a large company, and he intends to subdue still more. These Bahá’ís turned Persia upside down; now they have started in on the capital of Turkey. The Persian Government put 20,000 of them to the sword, hoping by this tactic to quench the fires of sedition. You should awaken to the danger; soon this perverse thing will blaze up here as well. It will consume the harvest of your life; it will burn up the whole world. Then you can do nothing, for it will be too late.”",
      "Actually that mild and submissive man, in that throne city of Asia Minor, was occupied solely with his calligraphy and his worship of God. He was striving to bring about not sedition but fellowship and peace. He was seeking to reconcile the followers of different faiths, not to drive them still further apart. He was of service to strangers and was helping to educate the native people. He was a refuge to the hapless and a horn of plenty to the poor. He invited all comers to the oneness of humankind; he shunned hostility and malice.",
      "The Persian ambassador, however, wielded enormous power, and he had maintained close ties with the ministers for a very long time. He prevailed on a number of persons to insinuate themselves into various gatherings and there to make every kind of false charge against the believers. Urged on by the oppressors, spies began to surround Mishkín-Qalam. Then, as instructed by the ambassador, they carried reports to the Prime Minister, stating that the individual in question was stirring up mischief day and night, that he was a troublemaker, a rebel and a criminal. The result was, they jailed him and they sent him away to Gallipoli, where he joined our own company of victims. They despatched him to Cyprus and ourselves to the ‘Akká prison. On the island of Cyprus, Jináb-i-Mishkín was held prisoner in the citadel at Famagusta, and in this city he remained, a captive, from the year 85 till 94.",
      "When Cyprus passed out of Turkish hands, Mishkín-Qalam was freed and betook himself to his Well-Beloved in the city of ‘Akká, and here he lived encompassed by the grace of Bahá’u’lláh, producing his marvelous calligraphs and sending them about. He was at all times joyous of spirit, ashine with the love of God, like a candle burning its life away, and he was a consolation to all the believers.",
      "After the ascension of Bahá’u’lláh, Mishkín-Qalam remained loyal, solidly established in the Covenant. He stood before the violators like a brandished sword. He would never go half way with them; he feared no one but God; not for a moment did he falter, nor ever fail in service.",
      "Following the ascension he made a journey to India, where he associated with the lovers of truth. He spent some time there, making fresh efforts every day. When I learned that he was getting helpless, I sent for him at once and he came back to this Most Great Prison, to the joy of the believers, who felt blessed to have him here again. He was at all times my close companion. He had amazing verve, intense love. He was a compendium of perfections: believing, confident, serene, detached from the world, a peerless companion, a wit—and his character like a garden in full bloom. For the love of God, he left all good things behind; he closed his eyes to success, he wanted neither comfort nor rest, he sought no wealth, he wished only to be free from the defilement of the world. He had no ties to this life, but spent his days and nights supplicating and communing with God. He was always smiling, effervescing; he was spirit personified, love embodied. For sincerity and loyalty he had no match, nor for patience and inner calm. He was selflessness itself, living on the breaths of the spirit.",
      "If he had not been in love with the Blessed Beauty, if he had not set his heart on the Realm of Glory, every worldly pleasure could have been his. Wherever he went, his many calligraphic styles were a substantial capital, and his great accomplishment brought him attention and respect from rich and poor alike. But he was hopelessly enamored of man’s one true Love, and thus he was free of all those other bonds, and could float and soar in the spirit’s endless sky.",
      "Finally, when I was absent, he left this darksome, narrow world and hastened away to the land of lights. There, in the haven of God’s boundless mercy, he found infinite rewards. Unto him be praise and salutations, and the Supreme Companion’s tender grace."
    ]
  },
  {
    id: "offering-in-prayer",
    theme: "prayer",
    author: "Abu’l-Qasim Faizi",
    book: "Unsigned transcript of a talk by Hand of the Cause of God Abu’l-Qasim Faizi",
    chapter: "Our Offering in Prayer",
    sourcePages: "Melbourne, 26 November 1969",
    sourceDetail:
      "From Bahá'í Stories; Abu’l-Qasim Faizi, Melbourne, 26 November 1969.",
    title: "Our offering in prayer.",
    quote: "Take your nothingness to Him.",
    readTime: "2 minute read",
    tags: ["Prayer", "Humility", "The Báb", "Nothingness", "Devotion"],
    summary:
      "Abu’l-Qasim Faizi tells how the Báb describes the one gift a soul can bring before God.",
    source: "https://bahaistories.com/subject/prayer",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Lotus_Temple_in_New_Delhi_03-2016.jpg",
    featureImageAlt: "The Bahá'í House of Worship known as the Lotus Temple in New Delhi",
    story: [
      "Our Offering in Prayer",
      "“To me, many of the hard problems of all the religions of God have been explained by the Báb, very easily. He brought these things from heaven to earth, and said this is what it means…",
      "“Why do we pray? The Báb says, when we pray, what do we take to God? What do we talk to Him of, what do we offer Him? Do you offer your knowledge? He is the Source of knowledge. Do you offer Him your wealth? Do you offer Him your strength, the strength of body or mental strength? All these things are not even worthy of being mentioned in the sight of God.",
      "“Therefore, why do we pray? The Báb says, I will give you an example. Suppose you want to go and visit a king. You will go here and there and ask many people: what is it that the king does not have in his treasury? I would like to take it as a gift to him. And, for instance, suppose somebody will say if you take a moonstone, he does not have it, then you will take it.",
      "\"Now, if you take the whole treasure of the world, God has it. The whole knowledge of the world He is the source of it. Strength? He is the source of Power. But the Báb says, as I advise you and tell you, there is one thing that God does not have in His treasure house, and that is NOTHINGNESS. Take your nothingness to Him. When you sit down in front of Him and pray, have an attitude that you are nothing as compared with God. You take that attitude, and He says this will immediately be accepted.\""
    ]
  },
  {
    id: "ali-najaf-abadi",
    theme: "devotion",
    author: "‘Abdu'l-Bahá",
    book: "Memorials of the Faithful",
    chapter: "‘Alí Najaf-Ábádí",
    sourcePages: "p. 21",
    sourceDetail:
      "From the Bahá'í Reference Library; ‘Abdu'l-Bahá, Memorials of the Faithful.",
    title: "‘Alí Najaf-Ábádí.",
    quote: "he turned his eyes away from this world of dust",
    readTime: "2 minute read",
    tags: ["Devotion", "Pilgrimage", "Prayer", "Detachment", "Steadfastness"],
    summary:
      "A brief complete memorial of a quiet believer who journeyed, served, prayed, and died detached from the world.",
    source: "https://www.bahai.org/library/authoritative-texts/abdul-baha/memorials-faithful/3",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Shrine_of_The_Bab.jpg",
    featureImageAlt: "The Shrine of the Báb and gardens in Haifa",
    story: [
      "Also among the emigrants and near neighbors was Áqá ‘Alí Najaf-Ábádí. When this spiritual young man first listened to the call of God he set his lips to the holy cup and beheld the glory of the Speaker on the Mount. And when, by grace of the light, he had attained positive knowledge, he journeyed to the Most Great Prison, where he witnessed the substance of knowledge itself, and arrived at the high station of indubitable truth.",
      "For a long time he remained in and about the sacred city; he became the proverbial Ḥabíbu’lláh the Merchant, and spent his days relying upon God, in supplication and prayer. He was a man meek, quiet, uncomplaining, steadfast; in all things pleasing, worthy of praise. He won the approval of all the friends and was accepted and welcome at the Holy Threshold. During his latter days, when he felt that a happy end was in store for him, he again presented himself at the holy city of the Most Great Prison.",
      "Upon arrival he fell ill, weakened, passed his hours in supplicating God. The breath of life ceased within him, the gates of flight to the supreme Kingdom were flung wide, he turned his eyes away from this world of dust and went onward to the Holy Place.",
      "‘Alí Najaf-Ábádí was tender and sensitive of heart, at all times mindful of God and remembering Him, and toward the close of his life detached, without stain, free from the contagion of this world. Sweetly, he gave up his corner of the earth, and pitched his tent in the land beyond. May God send upon him the pure savors of forgiveness, brighten his eyes with beholding the Divine Beauty in the Kingdom of Splendors, and refresh his spirit with the musk-scented winds that blow from the Abhá Realm.",
      "Unto him be salutation and praise. His sweet and holy dust lies in ‘Akká."
    ]
  },
  {
    id: "coal-miner-needs-no-translation",
    theme: "understanding",
    author: "Reginald Grant Barrow",
    book: "Mother's Stories: Stories of ‘Abdu'l-Bahá and Early Believers",
    chapter: "Universal Language - heart to heart",
    sourcePages: "p. 38",
    sourceDetail:
      "From Bahá'í Stories; Reginald Grant Barrow, Mother's Stories, p. 38.",
    title: "Anybody can understand Him.",
    quote: "Nothing ‘Abdu’l-Bahá says needs translating",
    readTime: "1 minute read",
    tags: ["Understanding", "Teaching", "Wonder", "Listening", "‘Abdu'l-Bahá"],
    collectionTags: ["Anecdotes"],
    summary:
      "A coal miner hears ‘Abdu’l-Bahá speak through an interpreter and insists the Master needs no translation.",
    source: "https://bahaistories.com/subject/universal-language-heart-heart",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Picture_of_Abdul-Baha.jpg",
    featureImageAlt: "A portrait photograph of ‘Abdu'l-Bahá",
    story: [
      "There is the story of the coal miner in California who had walked many miles to meet ‘Abdu’l-Bahá Who, of course spoke that evening as He always did through an interpreter. The coal miner became more and more impatient. Finally, unable to stand it any longer, he leaned toward the man sitting next to him. \"Why does that man continually interrupt the Master?\" he asked. The man explained, \"‘Abdu’l-Bahá is speaking in Persian it must, be translated.\" \"Translated!\" the coal miner was outraged.",
      "\"Nothing ‘Abdu’l-Bahá says needs translating - anybody can understand Him.\""
    ]
  },
  {
    id: "paul-haney-baby-insight",
    theme: "insight",
    author: "Agnes Parsons",
    book: "Agnes Parson’s Diary",
    chapter: "April 25, 1912",
    sourcePages: "April 25, 1912",
    sourceDetail:
      "From Bahá'í Stories; Agnes Parsons, Agnes Parsons' Diary, April 25, 1912.",
    title: "The baby had seen more.",
    quote: "You have much insight.",
    readTime: "1 minute read",
    tags: ["Insight", "Children", "Wonder", "Pilgrimage", "‘Abdu'l-Bahá"],
    collectionTags: ["Anecdotes"],
    summary:
      "After a child cries on seeing ‘Abdu’l-Bahá, Agnes Parsons hears the Master confirm that the adults may have missed what the baby perceived.",
    source: "https://bahaistories.com/subject/hands-cause",
    image: "",
    imageAlt: "",
    featureImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Baha%27i_House_of_Worship,_Kampala,_Uganda.jpg",
    featureImageAlt: "The Bahá'í House of Worship in Kampala, Uganda",
    story: [
      "Mr. and Mrs. Charles and Mariam Haney and the baby drove with ‘Abdu’l-Bahá in the morning. At the children’s meetings the baby [he was the future Hand of the Cause Mr. Paul Haney] had screamed when he saw ‘Abdu’l-Bahá and I thought at the time, that the child had probably been overwhelmed by seeing a greater spirituality in ‘Abdu’l-Bahá than many saw. Before they went to drive, I spoke of this to Mr. and Mrs. Haney, for the latter had shown such distress when it occurred. I believe Mr. Haney agreed with me. He said: “Three months before the child was born we were in Acca.” Afterward, when ‘Abdu’l-Bahá returned from the drive, I said to Him: “How was it with the baby?” “Everything was quite right” was His reply. I told Him I thought the baby had been conscious of more than we were, and ‘Abdu’l-Bahá’s answer was, “You have much insight.”"
    ]
  }
];
